In [1]:
import numpy as np

In [2]:
def BmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(-5.5)
        elif target == -1:
            trans_vector.append(-7)
        elif target == 3:
            trans_vector.append(-4)
        elif target == 4:
            trans_vector.append(-3.5)
        elif target == 4.5:
            trans_vector.append(-3)
        elif target == 6:
            trans_vector.append(-1.5)
        elif target == 6.5:
            trans_vector.append(-1)
        elif target == 7:
            trans_vector.append(1)
        elif target == 9:
            trans_vector.append(2.5)
        elif target == 10:
            trans_vector.append(4)
        elif target == 11.5:
            trans_vector.append(5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoBm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -5.5:
            trans_vector.append(2)
        elif target == -4:
            trans_vector.append(3)
        elif target == -3:
            trans_vector.append(4.5)
        elif target == -1.5:
            trans_vector.append(6)
        elif target == -1:
            trans_vector.append(6.5)
        elif target == 1:
            trans_vector.append(7)
        elif target == 1.5:
            trans_vector.append(8)
        elif target == -3.5:
            trans_vector.append(4)
        elif target == -7:
            trans_vector.append(-1)
        elif target == 2.5:
            trans_vector.append(9)
        elif target == 2:
            trans_vector.append(8.5)
        elif target == 4:
            trans_vector.append(10)
        elif target == 4.5:
            trans_vector.append(11)
        elif target == 5:
            trans_vector.append(11.5)
        elif target == 9:
            trans_vector.append(15.5)
        elif target == 8:
            trans_vector.append(14)
        elif target == 6.5:
            trans_vector.append(13)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def EmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(-1.5)
        elif target == 3:
            trans_vector.append(1)
        elif target == 4:
            trans_vector.append(1.5)
        elif target == 4.5:
            trans_vector.append(2)
        elif target == 6:
            trans_vector.append(4)
        elif target == 6.5:
            trans_vector.append(4.5)
        elif target == 7:
            trans_vector.append(5)
        elif target == 9:
            trans_vector.append(6.5)
        elif target == 10:
            trans_vector.append(8)
        elif target == 11.5:
            trans_vector.append(9)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoEm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 5:
            trans_vector.append(7)
        elif target == 6.5:
            trans_vector.append(9)
        elif target == 8:
            trans_vector.append(10)
        elif target == 9:
            trans_vector.append(11.5)
        elif target == -5.5:
            trans_vector.append(-3)
        elif target == -1.5:
            trans_vector.append(2)
        elif target == -1:
            trans_vector.append(2.5)
        elif target == 1:
            trans_vector.append(3)
        elif target == 1.5:
            trans_vector.append(4)
        elif target == 2.5:
            trans_vector.append(5)
        elif target == 4.5:
            trans_vector.append(6.5)
        elif target == 2:
            trans_vector.append(4.5)
        elif target == -4:
            trans_vector.append(-2)
        elif target == -3:
            trans_vector.append(-1)
        elif target == -3.5:
            trans_vector.append(-1.5)
        elif target == -7:
            trans_vector.append(-5)
        elif target == 4:
            trans_vector.append(6)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [3]:
def count_number(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

In [4]:
BmtoC_list = BmtoC([7,7,7,7, 6,6, 4.5,4.5,  0,0,0,0,  3,3,3,3,
                    2,2,2,2, -1,-1,2,2,  -1,-1,-1,-1,  0,0,0,0,
                    3,3,4.5,4.5, 7,7,7,7, 7,7,7,7, 0,0,0,0,
                    2,2,0,0,  0,0,0,0,  -1,-1,-1,-1,  2,2,3,3,
                    0,0,0,0,   2,2,4.5,4.5,  4.5,4.5,4.5,4.5,  -1,-1,-1,-1,
                    -1,-1,-1,-1,  3,3,3,3,  3,3,-1,-1,  -1,-1,-1,-1,
                    0,0,0,0,  3,3,3,3,  4.5,4.5,0,0,  0,0,0,0,
                    0,0,0,0,   9,9,9,9,  7,7,6.5,6.5,  0,0,0,0])
EmtoC_list = EmtoC([4.5,4.5,7,7,  7,7,0,0,  7,7,0,0,  9,9,0,0,
                    7,7,7,7,9,9,7,7,  6,6,4.5,4.5, 4,3,2,2])

In [5]:
minor_list = BmtoC_list+EmtoC_list
count_number(minor_list)
# len(minor_list)

{0: 46,
 1: 15,
 2.5: 4,
 2: 4,
 4: 2,
 5: 12,
 6.5: 4,
 1.5: 1,
 -7: 24,
 -5.5: 12,
 -4: 18,
 -3: 12,
 -1: 2,
 -1.5: 4}

In [6]:
#映射顺序 0,1,1.5,2,2.5,4,5,6.5,-1,-1.5,-3,-4,-5.5,-7
def minor_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 1.5:
            trans_vector.append(2)
        elif target == 2:
            trans_vector.append(3)
        elif target == 2.5:
            trans_vector.append(4)
        elif target == 4:
            trans_vector.append(5)
        elif target == 5:
            trans_vector.append(6)
        elif target == 6.5:
            trans_vector.append(7)
        elif target == -1:
            trans_vector.append(8)
        elif target == -1.5:
            trans_vector.append(9)
        elif target == -3:
            trans_vector.append(10)
        elif target == -4:
            trans_vector.append(11)
        elif target == -5.5:
            trans_vector.append(12)
        elif target == -7:
            trans_vector.append(13)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [7]:
reflect_minor_list = minor_reflect(minor_list)
print(reflect_minor_list)
len(reflect_minor_list)

[1, 1, 1, 1, 9, 9, 10, 10, 0, 0, 0, 0, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 12, 12, 13, 13, 13, 13, 0, 0, 0, 0, 11, 11, 10, 10, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 12, 12, 0, 0, 0, 0, 0, 0, 13, 13, 13, 13, 12, 12, 11, 11, 0, 0, 0, 0, 12, 12, 10, 10, 10, 10, 10, 10, 13, 13, 13, 13, 13, 13, 13, 13, 11, 11, 11, 11, 11, 11, 13, 13, 13, 13, 13, 13, 0, 0, 0, 0, 11, 11, 11, 11, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 1, 1, 8, 8, 0, 0, 0, 0, 3, 3, 6, 6, 6, 6, 0, 0, 6, 6, 0, 0, 7, 7, 0, 0, 6, 6, 6, 6, 7, 7, 6, 6, 5, 5, 3, 3, 2, 1, 9, 9]


160

In [8]:
def markoving(darray, vector):
    num = len(vector)
    for i in range(num-1):   #最后一个不用考虑
        row = vector[i]
        column = vector[i+1]
        darray[row][column] += 1
    return darray

In [9]:
minor_array = np.zeros((14,14))
#Bm1
Bm1 = reflect_minor_list[0:64]

Bm5 = reflect_minor_list[64:96]

Bm7 = reflect_minor_list[96:128]

Em1 = reflect_minor_list[128:160]


minor_array = markoving(minor_array,Bm1)
minor_array = markoving(minor_array,Bm5)

minor_array = markoving(minor_array,Bm7)

minor_array = markoving(minor_array,Em1)

print(minor_array)

[[35.  0.  0.  0.  1.  0.  2.  1.  0.  0.  0.  3.  2.  1.]
 [ 1. 11.  0.  0.  0.  0.  0.  0.  1.  2.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  2.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  1.  8.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  2.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  1.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  8.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2. 13.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  7.  2.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  2. 19.]]


In [10]:
def normalize_matrix(matrix):
    mat_size = matrix.shape[0]
    init_array = np.zeros((mat_size,mat_size))
    sum_row_list=[]
    for i in range(mat_size):
        count=0
        for j in range(mat_size):
            count+=matrix[i][j]
        sum_row_list.append(count)
    for k in range(mat_size):
        if sum_row_list[k] == 0:
            init_array[k][k] = 0
        else:
            init_array[k][k] = 1/sum_row_list[k]
    result = np.dot(init_array,matrix)
    
    return result

def sum_rows(matrix):
    sum_row_list1=[]
    for ii in range(len(matrix)):
        count=0
        for jj in range(len(matrix[ii])):
            count+=matrix[ii][jj]
        sum_row_list1.append(count)
    print(sum_row_list1)

In [11]:
markov_minor = normalize_matrix(minor_array)
print(markov_minor)
sum_rows(markov_minor)

[[0.77777778 0.         0.         0.         0.02222222 0.
  0.04444444 0.02222222 0.         0.         0.         0.06666667
  0.04444444 0.02222222]
 [0.06666667 0.73333333 0.         0.         0.         0.
  0.         0.         0.06666667 0.13333333 0.         0.
  0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.25       0.5        0.         0.
  0.25       0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.25       0.         0.         0.75       0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.5
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.16666667 0.         0.         0.         0.         0.08333333
  0.66666667 0.08333333 0.         0.         0.     

In [12]:
#邻接矩阵

def generate_adj(darray, vector):
    num = len(vector)
    for i in range(num-1):
        row = vector[i]
        column = vector[i+1]
        darray[row][column] = 1
    return darray

In [13]:
adj_minor = np.zeros((14,14))

adj_minor = generate_adj(adj_minor,Bm1)

adj_minor = generate_adj(adj_minor,Bm5)

adj_minor = generate_adj(adj_minor,Bm7)

adj_minor = generate_adj(adj_minor,Em1)


print(adj_minor)

[[1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [14]:
#邻接矩阵调参数
k=8
x = 0.8

i = 0
Iter_adj_minor = 1
for i in range(k):
    Iter_adj_minor = np.dot(adj_minor,Iter_adj_minor)
    
Iter_adj_minor = normalize_matrix(Iter_adj_minor)

markov_minor_final = x*markov_minor + (1-x)*Iter_adj_minor
sum_rows(markov_minor_final)
print(markov_minor_final)

[1.0000000000000002, 0.9999999999999999, 1.0, 1.0, 1.0, 1.0, 0.9999999999999998, 0.9999999999999999, 1.0000000000000002, 0.9999999999999999, 1.0, 0.9999999999999999, 1.0, 1.0]
[[6.57137771e-01 8.24448970e-03 3.29420220e-04 1.39055263e-03
  2.81175797e-02 4.56696215e-03 5.07917399e-02 3.26845419e-02
  2.43072193e-03 2.43072193e-03 1.72406564e-02 8.13490257e-02
  6.35712479e-02 4.97145690e-02]
 [8.82822206e-02 5.94908027e-01 3.36982088e-04 1.43839334e-03
  1.04215669e-02 4.69060973e-03 1.54491587e-02 1.51121766e-02
  5.58075508e-02 1.09140884e-01 1.70797901e-02 2.78225077e-02
  2.78225077e-02 3.16876244e-02]
 [3.50000000e-02 8.08250988e-01 3.35968379e-04 1.47233202e-03
  1.05335968e-02 4.81225296e-03 1.56818182e-02 1.53458498e-02
  2.55928854e-03 2.55928854e-03 1.68873518e-02 2.75889328e-02
  2.75889328e-02 3.13833992e-02]
 [3.49316755e-02 7.96503755e-03 2.00707867e-01 4.02363659e-01
  1.06549304e-02 6.06918626e-03 2.17431983e-01 1.67241167e-02
  2.36365875e-03 2.36365875e-03 1.56838606e

In [15]:
#开始进行迭代
init_array = np.array([1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14,1/14]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_minor_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.15234775]
 [0.12628954]
 [0.01470739]
 [0.05877771]
 [0.05458348]
 [0.03829818]
 [0.08504755]
 [0.0500227 ]
 [0.03484381]
 [0.04817727]
 [0.08543155]
 [0.08229327]
 [0.0717432 ]
 [0.09743658]]
1 	 [[0.19130852]
 [0.11068356]
 [0.01213933]
 [0.04036694]
 [0.04587287]
 [0.02579739]
 [0.08814096]
 [0.04360891]
 [0.02312665]
 [0.04161924]
 [0.08791223]
 [0.09436382]
 [0.0772703 ]
 [0.11778927]]
2 	 [[0.21056526]
 [0.09791069]
 [0.00843528]
 [0.02794576]
 [0.04131736]
 [0.02091435]
 [0.08607881]
 [0.04183183]
 [0.01760599]
 [0.03645552]
 [0.08908526]
 [0.10500185]
 [0.08331814]
 [0.13353391]]
3 	 [[0.22013257]
 [0.08662949]
 [0.00593845]
 [0.02099101]
 [0.03891303]
 [0.01877103]
 [0.08274558]
 [0.04126   ]
 [0.01471577]
 [0.03233834]
 [0.08979432]
 [0.11354637]
 [0.08847974]
 [0.14574429]]
4 	 [[0.22463106]
 [0.07758531]
 [0.00453994]
 [0.01733174]
 [0.03763217]
 [0.01765931]
 [0.07975468]
 [0.04093867]
 [0.01295764]
 [0.02893881]
 [0.09025719]
 [0.12008852]
 [0.09251601]
 [0.155168

In [16]:
minor_list = [0,1,1.5,2,2.5,4,5,6.5,-1,-1.5,-3,-4,-5.5,-7]
p_list1 = []

i = 0
for i in range(len(minor_list)):
    target_list = res[i]
    p_list1.append(target_list[0])
print(p_list1)

reflect_0 = minor_reflect([0])
print(reflect_0)
reflect_1 = minor_reflect([1,-7])
print(reflect_1)
reflect_1_5 = minor_reflect([1.5])
print(reflect_1_5)
reflect_2 = minor_reflect([2])
print(reflect_2)
reflect_2_5 =minor_reflect([2.5,-5.5])
print(reflect_2_5)
reflect_4 = minor_reflect([4,-4])
print(reflect_4)
reflect_5 = minor_reflect([5,-3])
print(reflect_5)
reflect_6_5 = minor_reflect([6.5,-1.5])
print(reflect_6_5)
reflect_7 = minor_reflect([-1])
print(reflect_7)


minor_list_new = [4.5,1,1.5,2,2.5,4,5,6.5,-1]
p_list_new=[]
p_list_new.append(p_list1[0])
p_list_new.append(p_list1[1]+p_list1[13])
p_list_new.append(p_list1[2])
p_list_new.append(p_list1[3])
p_list_new.append(p_list1[4]+p_list1[12])
p_list_new.append(p_list1[5]+p_list1[11])
p_list_new.append(p_list1[6]+p_list1[10])
p_list_new.append(p_list1[7]+p_list1[9])
p_list_new.append(p_list1[8])

print(minor_list_new)
print(p_list_new)

minor_80 = np.random.choice(minor_list_new, 80, p=p_list_new)

[0.22339788745646946, 0.057339340983289806, 0.0028736070544701153, 0.012732425735689197, 0.03581461808908501, 0.015629136749963583, 0.07209169289060341, 0.039504721805051025, 0.009181331648601193, 0.018357773968135285, 0.08977611235094869, 0.1369186141163581, 0.10332590586181292, 0.18305683128952177]
[0]
[1, 13]
[2]
[3]
[4, 12]
[5, 11]
[6, 10]
[7, 9]
[8]
[4.5, 1, 1.5, 2, 2.5, 4, 5, 6.5, -1]
[0.22339788745646946, 0.24039617227281157, 0.0028736070544701153, 0.012732425735689197, 0.13914052395089793, 0.1525477508663217, 0.1618678052415521, 0.05786249577318631, 0.009181331648601193]


In [17]:
minor1 = CtoBm(minor_80[0:32])
minor2 = CtoEm(minor_80[32:48])
minor3 = CtoBm(minor_80[48:64])
minor4 = CtoBm(minor_80[64:80])

In [18]:
#Gmaj7
Gmaj7_list = [0,0,0,0, 2,2,2,2, 3,3,3,3, 0,0,0,0]

#映射顺序 0,2,3
def Gmaj7_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(1)
        elif target == 3:
            trans_vector.append(2)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [19]:
reflec_Gmaj7_list = Gmaj7_reflect(Gmaj7_list)

Gmaj7_array = np.zeros((3,3))
Gmaj7_array = markoving(Gmaj7_array,reflec_Gmaj7_list)
print(Gmaj7_array)

markov_Gmaj7 = normalize_matrix(Gmaj7_array)
print(markov_Gmaj7)
sum_rows(markov_Gmaj7)

[[6. 1. 0.]
 [0. 3. 1.]
 [1. 0. 3.]]
[[0.85714286 0.14285714 0.        ]
 [0.         0.75       0.25      ]
 [0.25       0.         0.75      ]]
[1.0, 1.0, 1.0]


In [20]:
#邻接矩阵
adj_Gmaj7 = np.zeros((3,3))

adj_Gmaj7 = generate_adj(adj_Gmaj7,reflec_Gmaj7_list)
print(adj_Gmaj7)

[[1. 1. 0.]
 [0. 1. 1.]
 [1. 0. 1.]]


In [21]:
k = 8
x = 0.8

i = 0
Iter_adj_Gmaj7 = 1
for i in range(k):
    Iter_adj_Gmaj7 = np.dot(adj_Gmaj7,Iter_adj_Gmaj7)

print(Iter_adj_Gmaj7)
Iter_adj_Gmaj7 = normalize_matrix(Iter_adj_Gmaj7)

markov_Gmaj7_final = x*markov_Gmaj7 + (1-x)*Iter_adj_Gmaj7
print(markov_Gmaj7_final)
sum_rows(markov_Gmaj7_final)

[[85. 86. 85.]
 [85. 85. 86.]
 [86. 85. 85.]]
[[0.75212054 0.18147321 0.06640625]
 [0.06640625 0.66640625 0.2671875 ]
 [0.2671875  0.06640625 0.66640625]]
[1.0, 1.0, 1.0]


In [22]:
#开始进行迭代
init_array = np.array([1/3,1/3,1/3]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_Gmaj7_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.36190476]
 [0.3047619 ]
 [0.33333333]]
1 	 [[0.3814966 ]
 [0.29090668]
 [0.32759673]]
2 	 [[0.3937792 ]
 [0.28484791]
 [0.32137289]]
3 	 [[0.40095192]
 [0.28262597]
 [0.3164221 ]]
4 	 [[0.40487634]
 [0.28211815]
 [0.31300551]]
5 	 [[0.40688138]
 [0.28226503]
 [0.31085359]]
6 	 [[0.40782419]
 [0.28258387]
 [0.30959193]]
7 	 [[0.40821738]
 [0.28288367]
 [0.30889895]]
8 	 [[0.40834786]
 [0.28310878]
 [0.30854336]]
9 	 [[0.40836593]
 [0.28325887]
 [0.3083752 ]]
10 	 [[0.40834456]
 [0.283351  ]
 [0.30830444]]
11 	 [[0.4083157 ]
 [0.28340382]
 [0.30828048]]
12 	 [[0.4082911 ]
 [0.28343219]
 [0.30827671]]
13 	 [[0.40827347]
 [0.28344638]
 [0.30828015]]
14 	 [[0.40826208]
 [0.28345287]
 [0.30828506]]
15 	 [[0.40825525]
 [0.28345545]
 [0.3082893 ]]
16 	 [[0.40825142]
 [0.28345621]
 [0.30829237]]
17 	 [[0.40824941]
 [0.28345623]
 [0.30829437]]
18 	 [[0.40824843]
 [0.28345601]
 [0.30829557]]
19 	 [[0.408248  ]
 [0.28345576]
 [0.30829624]]
20 	 [[0.40824784]
 [0.28345556]
 [0.3082966 ]]
21

In [23]:
#映射顺序 0,2,3
Gmaj7_list = [0,2,3]
p_list2 = []

i = 0
for i in range(len(Gmaj7_list)):
    target_list = res[i]
    p_list2.append(target_list[0])
print(p_list2)

#主歌大调：K=3，x=0.8
Gmaj7_8 = np.random.choice(Gmaj7_list, 8, p=p_list2)
Gmaj7 = Gmaj7_8.tolist()

[0.4082478926664859, 0.28345523921295, 0.3082968681205665]


In [24]:
#F7
F7_list = [0,0,0,0, 3,3,4.5,2, -1,-1,-1,-1, 2,2,2,2]

#映射顺序 0,2,3,4.5,-1
def F7_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(1)
        elif target == 3:
            trans_vector.append(2)
        elif target == 4.5:
            trans_vector.append(3)
        elif target == -1:
            trans_vector.append(4)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [25]:
reflec_F7_list = F7_reflect(F7_list)

F7_array = np.zeros((5,5))
F7_array = markoving(F7_array,reflec_F7_list)
print(F7_array)

markov_F7 = normalize_matrix(F7_array)
print(markov_F7)
sum_rows(markov_F7)

[[3. 0. 1. 0. 0.]
 [0. 3. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 3.]]
[[0.75 0.   0.25 0.   0.  ]
 [0.   0.75 0.   0.   0.25]
 [0.   0.   0.5  0.5  0.  ]
 [0.   1.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.75]]
[1.0, 1.0, 1.0, 1.0, 1.0]


In [26]:
#邻接矩阵
adj_F7 = np.zeros((5,5))

adj_F7 = generate_adj(adj_F7,reflec_F7_list)
print(adj_F7)

[[1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1.]]


In [27]:
k = 8
x = 0.8

i = 0
Iter_adj_F7 = 1
for i in range(k):
    Iter_adj_F7 = np.dot(adj_F7,Iter_adj_F7)

print(Iter_adj_F7)
Iter_adj_F7 = normalize_matrix(Iter_adj_F7)

markov_F7_final = x*markov_F7 + (1-x)*Iter_adj_F7
print(markov_F7_final)
sum_rows(markov_F7_final)

[[  1.  63.   8.   7.  57.]
 [  0. 128.   0.   0. 128.]
 [  0.  64.   1.   1.  63.]
 [  0.  64.   0.   0.  64.]
 [  0. 128.   0.   0. 128.]]
[[0.60147059 0.09264706 0.21176471 0.01029412 0.08382353]
 [0.         0.7        0.         0.         0.3       ]
 [0.         0.09922481 0.40155039 0.40155039 0.09767442]
 [0.         0.9        0.         0.         0.1       ]
 [0.         0.3        0.         0.         0.7       ]]
[1.0, 1.0, 0.9999999999999999, 1.0, 1.0]


In [28]:
#开始进行迭代
init_array = np.array([1/5,1/5,1/5,1/5, 1/5]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_F7_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.12029412]
 [0.41837437]
 [0.12266302]
 [0.0823689 ]
 [0.25629959]]
1 	 [[0.07235337]
 [0.46720006]
 [0.07472943]
 [0.0504937 ]
 [0.33522343]]
2 	 [[0.04351843]
 [0.48716975]
 [0.04532952]
 [0.03075245]
 [0.39322986]]
3 	 [[0.02617505]
 [0.49519465]
 [0.02741775]
 [0.01865007]
 [0.43256247]]
4 	 [[0.01574352]
 [0.49833562]
 [0.01655256]
 [0.01127906]
 [0.45808923]]
5 	 [[0.00946927]
 [0.49951387]
 [0.00998061]
 [0.00680875]
 [0.47422749]]
6 	 [[0.00569549]
 [0.49992346]
 [0.00601297]
 [0.0041052 ]
 [0.48426288]]
7 	 [[0.00342567]
 [0.50004427]
 [0.00362062]
 [0.00247314]
 [0.4904363 ]]
8 	 [[0.00206044]
 [0.50006434]
 [0.00217929]
 [0.00148912]
 [0.4942068 ]]
9 	 [[0.00123929]
 [0.50005442]
 [0.00131142]
 [0.00089631]
 [0.49649855]]
10 	 [[0.0007454 ]
 [0.50003928]
 [0.00078904]
 [0.00053936]
 [0.49788692]]
11 	 [[4.48335098e-04]
 [5.00026348e-01]
 [4.74688990e-04]
 [3.24513175e-04]
 [4.98726114e-01]]
12 	 [[2.69660375e-04]
 [5.00016978e-01]
 [2.85553098e-04]
 [1.95226762e-04]
 

In [29]:
#映射顺序 0,2,3,4.5,-1
F7_list = [0,2,3,4.5,-1]
p_list3 = []

i = 0
for i in range(len(F7_list)):
    target_list = res[i]
    p_list3.append(target_list[0])
print(p_list3)

#主歌大调：K=3，x=0.8
F7_8 = np.random.choice(F7_list, 8, p=p_list3)
F7 = F7_8.tolist()

[1.8270471732576316e-12, 0.5000000000001333, 1.9352927118228576e-12, 1.3232989154015971e-12, 0.4999999999947839]


In [30]:
seq = minor1 + minor2 + minor3 + Gmaj7 + F7 + minor4
print(seq)

[10, 7, 9, 11, 7, 11, 11, 10, 7, 8.5, 7, 11.5, 11, 9, 7, 11, 7, 10, 9, 11, 11, 7, 7, 11, 10, 10, 11, 7, 13, 7, 10, 11, 3, 3, 5, 6.5, 6, 9, 7, 9, 6.5, 5, 7, 6.5, 5, 5, 6.5, 6, 7, 6.5, 10, 9, 7, 11.5, 10, 11, 6.5, 11, 13, 10, 10, 11.5, 13, 13, 2, 0, 0, 0, 0, 0, 2, 2, 2.0, -1.0, 2.0, 2.0, -1.0, 2.0, 2.0, -1.0, 13, 7, 7, 8.5, 10, 9, 10, 7, 9, 9, 11, 7, 9, 9, 9, 7]


In [31]:
def post_process(vector):
    vector[6] = 0
    vector[5] = 0
    vector[9] = 0
    vector[22] = 0
    vector[23] = 0
    vector[24] = 0
    
    vector[38] = 0
    vector[39] = 0
    vector[40] = 0
    
    vector[47] = 0
    vector[48] = 0
    

    vector[53] = 0
    vector[54] = 0
        
    vector[86] = 0
    vector[87] = 0
    vector[89] = 0
    vector[90] = 0
    
    for i in range(len(vector)):
        if vector[i] == 0:
            vector[i] = vector[i-1]
    return vector

seq = post_process(seq)

In [32]:
import mido
from mido import Message, MidiFile, MidiTrack

In [33]:
import math

def map_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 4:
        result = 6
    elif num == 4.5:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result   


def map2_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 3.5:
        result = 6
    elif num == 4:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result 
        
        
def toMidi(vector):
    
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target > 0:
            base = 59   #基数是59
            int_part = math.floor(target)     #得到target的整数部分
            times = math.floor(int_part/7)    #整数部分是由多少个7组成的
            base += times*12

            remain = target - times*7        #得到剩余部分
            base += map_remain(remain)
            trans_vector.append(base)
#         elif target == 0:
#             last = trans_vector[len(trans_vector)]
#             trans_vector.append(last)
        else:  #target < 0
            base = 60   #基数是60
            target = abs(target)
            int_part = math.floor(target)
            times = math.floor(int_part/7)
            base -= times*12
            
            remain = target - times*7
            base -= map2_remain(remain)
            trans_vector.append(base)
    return trans_vector

toMidi(seq)

[76,
 71,
 74,
 77,
 71,
 71,
 71,
 76,
 71,
 71,
 71,
 78,
 77,
 74,
 71,
 77,
 71,
 76,
 74,
 77,
 77,
 71,
 71,
 71,
 71,
 76,
 77,
 71,
 81,
 71,
 76,
 77,
 64,
 64,
 67,
 70,
 69,
 74,
 74,
 74,
 74,
 67,
 71,
 70,
 67,
 67,
 70,
 70,
 70,
 70,
 76,
 74,
 71,
 71,
 71,
 77,
 70,
 77,
 81,
 76,
 76,
 78,
 81,
 81,
 62,
 62,
 62,
 62,
 62,
 62,
 62,
 62,
 62,
 59,
 62,
 62,
 59,
 62,
 62,
 59,
 81,
 71,
 71,
 73,
 76,
 74,
 74,
 74,
 74,
 74,
 74,
 71,
 74,
 74,
 74,
 71]

In [34]:
mid = MidiFile()       #给自己的文件定的.mid后缀
track = MidiTrack()    #定义声部，一个MidoTrack()就是一个声部

In [35]:
def beat(time):            #与mido的拍子互换  
    time /= 60 * 1000  
    time = 1/time  
    return time  

def yin(yin,pai,qian=0,unit = track, liang=64,qi=2): #yin是音，pai是指时间（节拍），
    if type(yin)== str:               #qian是是音前多少拍
        yin = num(yin)                #liang是音量

    unit.append(Message('program_change',channel=0,program=qi,time=0))
    unit.append(Message('note_on',note=yin,velocity=liang,time=qian,channel=0))
    unit.append(Message('note_off',note=yin,velocity=liang,time=int(beat(pai)),channel=0))

In [36]:
def find_nearest(num, vector):
    result = num
    mark = 100
    length = len(vector)
    for i in range(length):
        instance = abs(num - vector[i])
        if mark > instance:
            mark = instance
            result = vector[i]
        else:
            continue
    return result

In [37]:
#后处理

fuge_sequence = seq
midi_sequence = toMidi(fuge_sequence)

bules_list = [-1,2,3,4,4.5,6,6.5,7,9,10,11,11.5,13]
midi_bules_list = toMidi(bules_list)
i = 0 
for i in range(len(midi_sequence)):
    target = fuge_sequence[i]
    midi_target = midi_sequence[i]
    if target>11.5:
        midi_target -= 12
    elif target < 2:
        midi_target += 12
    
    if midi_target in midi_bules_list:
        yin(midi_target,120, 0,track,80,2)
    else:
        midi_target = find_nearest(midi_target,midi_bules_list)
        yin(midi_target,120, 0,track,80,2)    

In [38]:
mid.tracks.append(track)
mid.save('C:\\Users\\Administrator\\Desktop\\2020Summer\\newBlues1.mid')