In [1]:
import numpy as np

In [2]:
def BmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(-5.5)
        elif target == 3:
            trans_vector.append(-4)
        elif target == 4.5:
            trans_vector.append(-3)
        elif target == 6:
            trans_vector.append(-1.5)
        elif target == 7:
            trans_vector.append(1)
        elif target == 9:
            trans_vector.append(2.5)
        elif target == 10:
            trans_vector.append(4)
        elif target == 11.5:
            trans_vector.append(5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoBm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -5.5:
            trans_vector.append(2)
        elif target == -4:
            trans_vector.append(3)
        elif target == -3:
            trans_vector.append(4.5)
        elif target == -1.5:
            trans_vector.append(6)
        elif target == 1:
            trans_vector.append(7)
        elif target == 2.5:
            trans_vector.append(9)
        elif target == 2:
            trans_vector.append(8.5)
        elif target == 4:
            trans_vector.append(10)
        elif target == 4.5:
            trans_vector.append(11)
        elif target == 5:
            trans_vector.append(11.5)
        elif target == 9:
            trans_vector.append(15.5)
        elif target == 8:
            trans_vector.append(14)
        elif target == 6.5:
            trans_vector.append(13)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def EmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 7:
            trans_vector.append(5)
        elif target == 9:
            trans_vector.append(6.5)
        elif target == 10:
            trans_vector.append(8)
        elif target == 11.5:
            trans_vector.append(9)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoEm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 5:
            trans_vector.append(7)
        elif target == 6.5:
            trans_vector.append(9)
        elif target == 8:
            trans_vector.append(10)
        elif target == 9:
            trans_vector.append(11.5)
        elif target == -5.5:
            trans_vector.append(-3)
        elif target == -1.5:
            trans_vector.append(2)
        elif target == 1:
            trans_vector.append(3)
        elif target == 2.5:
            trans_vector.append(5)
        elif target == 4.5:
            trans_vector.append(6.5)
        elif target == 2:
            trans_vector.append(4.5)
        elif target == -4:
            trans_vector.append(-2)
        elif target == -3:
            trans_vector.append(-1)
        elif target == 4:
            trans_vector.append(6)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [3]:
def count_number(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

In [4]:
BmtoC_list = BmtoC([7,7,0,0,7,7,7,7,7,7,2,2,0,0,0,0,
                    0,0,0,0,7,7,9,9,10,10,11.5,11.5,9,9,10,10,
                    7,7,7,7,0,0,0,0,10,11.5,9,9,0,0,0,0,
                    0,0,7,7,9,9,11.5,11.5,11.5,11.5,11.5,11.5,10,10,9,9,
                    10,10,9,9,9,9,10,10,7,7,7,7,0,0,4.5,4.5,
                    7,7,6,6,3,3,4.5,4.5,2,2,2,2,2,2,4.5,4.5,
                    7,7,7,7, 0,0,0,0, 6,6,6,6, 4.5,4.5,4.5,4.5,
                    0,0,0,0, 2,2,3,3, 4.5,4.5,7,7, 4.5,4.5,7,7])
EmtoC_list = EmtoC([10,10,10,10,  11.5,11.5,9,9,   10,10,7,7, 7,7,7,7,
                    0,0,7,7, 9,9,10,10, 11.5,11.5,9,9, 10,10,0,0])

In [5]:
minor_list = BmtoC_list+EmtoC_list
count_number(minor_list)
# len(minor_list)

{0: 34,
 1: 30,
 2.5: 14,
 4: 11,
 5: 17,
 6.5: 6,
 8: 10,
 9: 4,
 -5.5: 10,
 -4: 4,
 -3: 14,
 -1.5: 6}

In [6]:
#映射顺序 0,1,2.5,4,5,6.5,8,9,-1.5,-3,-4,-5.5
def minor_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 2.5:
            trans_vector.append(2)
        elif target == 4:
            trans_vector.append(3)
        elif target == 5:
            trans_vector.append(4)
        elif target == 6.5:
            trans_vector.append(5)
        elif target == 8:
            trans_vector.append(6)
        elif target == 9:
            trans_vector.append(7)
        elif target == -1.5:
            trans_vector.append(8)
        elif target == -3:
            trans_vector.append(9)
        elif target == -4:
            trans_vector.append(10)
        elif target == -5.5:
            trans_vector.append(11)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [7]:
reflect_minor_list = minor_reflect(minor_list)
print(reflect_minor_list)
len(reflect_minor_list)

[1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 2, 2, 3, 3, 1, 1, 1, 1, 0, 0, 0, 0, 3, 4, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 2, 2, 3, 3, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 0, 0, 9, 9, 1, 1, 8, 8, 10, 10, 9, 9, 11, 11, 11, 11, 11, 11, 9, 9, 1, 1, 1, 1, 0, 0, 0, 0, 8, 8, 8, 8, 9, 9, 9, 9, 0, 0, 0, 0, 11, 11, 10, 10, 9, 9, 1, 1, 9, 9, 1, 1, 6, 6, 6, 6, 7, 7, 5, 5, 6, 6, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 5, 5, 6, 6, 7, 7, 5, 5, 6, 6, 0, 0]


160

In [8]:
def markoving(darray, vector):
    num = len(vector)
    for i in range(num-1):   #最后一个不用考虑
        row = vector[i]
        column = vector[i+1]
        darray[row][column] += 1
    return darray

In [9]:
minor_array = np.zeros((12,12))
#Bm1
Bm1 = reflect_minor_list[0:16]
Bm2 = reflect_minor_list[16:32]
Bm3 = reflect_minor_list[32:48]
Bm4 = reflect_minor_list[48:64]
Bm5 = reflect_minor_list[64:80]
Bm6 = reflect_minor_list[80:96]
Bm7 = reflect_minor_list[96:112]
Bm8 = reflect_minor_list[112:128]
Em1 = reflect_minor_list[128:144]
Em2 = reflect_minor_list[144:160]

minor_array = markoving(minor_array,Bm1)
minor_array = markoving(minor_array,Bm2)
minor_array = markoving(minor_array,Bm3)
minor_array = markoving(minor_array,Bm4)
minor_array = markoving(minor_array,Bm5)
minor_array = markoving(minor_array,Bm6)
minor_array = markoving(minor_array,Bm7)
minor_array = markoving(minor_array,Bm8)
minor_array = markoving(minor_array,Em1)
minor_array = markoving(minor_array,Em2)
print(minor_array)

[[23.  3.  0.  1.  1.  0.  0.  0.  1.  1.  0.  1.]
 [ 4. 20.  2.  0.  0.  0.  0.  0.  1.  1.  0.  1.]
 [ 1.  0.  8.  3.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  5.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  1. 12.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  3.  3.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  1.  0.  6.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  4.  1.  1.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  8.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  2.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  7.]]


In [10]:
def normalize_matrix(matrix):
    mat_size = matrix.shape[0]
    init_array = np.zeros((mat_size,mat_size))
    sum_row_list=[]
    for i in range(mat_size):
        count=0
        for j in range(mat_size):
            count+=matrix[i][j]
        sum_row_list.append(count)
    for k in range(mat_size):
        if sum_row_list[k] == 0:
            init_array[k][k] = 0
        else:
            init_array[k][k] = 1/sum_row_list[k]
    result = np.dot(init_array,matrix)
    
    return result

def sum_rows(matrix):
    sum_row_list1=[]
    for ii in range(len(matrix)):
        count=0
        for jj in range(len(matrix[ii])):
            count+=matrix[ii][jj]
        sum_row_list1.append(count)
    print(sum_row_list1)

In [11]:
markov_minor = normalize_matrix(minor_array)
print(markov_minor)
sum_rows(markov_minor)

[[0.74193548 0.09677419 0.         0.03225806 0.03225806 0.
  0.         0.         0.03225806 0.03225806 0.         0.03225806]
 [0.13793103 0.68965517 0.06896552 0.         0.         0.
  0.         0.         0.03448276 0.03448276 0.         0.03448276]
 [0.07692308 0.         0.61538462 0.23076923 0.07692308 0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.1        0.2        0.5        0.2        0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.125      0.0625     0.75       0.0625
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.5        0.         0.         0.         0.         0.        ]
 [0.1        0.         0.         0.         0.1        0.
  0.6        0.2        0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.         0.5        0.     

In [12]:
#邻接矩阵

def generate_adj(darray, vector):
    num = len(vector)
    for i in range(num-1):
        row = vector[i]
        column = vector[i+1]
        darray[row][column] = 1
    return darray

In [13]:
adj_minor = np.zeros((12,12))

adj_minor = generate_adj(adj_minor,Bm1)
adj_minor = generate_adj(adj_minor,Bm2)
adj_minor = generate_adj(adj_minor,Bm3)
adj_minor = generate_adj(adj_minor,Bm4)
adj_minor = generate_adj(adj_minor,Bm5)
adj_minor = generate_adj(adj_minor,Bm6)
adj_minor = generate_adj(adj_minor,Bm7)
adj_minor = generate_adj(adj_minor,Bm8)
adj_minor = generate_adj(adj_minor,Em1)
adj_minor = generate_adj(adj_minor,Em2)

print(adj_minor)

[[1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [14]:
#邻接矩阵调参数
k=8
x = 0.8

i = 0
Iter_adj_minor = 1
for i in range(k):
    Iter_adj_minor = np.dot(adj_minor,Iter_adj_minor)
    
Iter_adj_minor = normalize_matrix(Iter_adj_minor)

markov_minor_final = x*markov_minor + (1-x)*Iter_adj_minor
sum_rows(markov_minor_final)
print(markov_minor_final)

[0.9999999999999999, 1.0, 1.0, 1.0000000000000002, 1.0, 1.0, 1.0000000000000002, 0.9999999999999998, 1.0, 1.0000000000000002, 1.0, 1.0]
[[6.16069553e-01 1.00978021e-01 2.03942243e-02 4.59448716e-02
  4.64434952e-02 6.71323950e-03 2.10356828e-03 6.50547967e-04
  4.04872806e-02 5.71145594e-02 1.25889472e-02 5.05116924e-02]
 [1.32930324e-01 5.75448863e-01 7.51888338e-02 1.97272536e-02
  2.01704484e-02 6.41542608e-03 1.94133845e-03 5.65254982e-04
  4.23961781e-02 5.95311054e-02 1.29165849e-02 5.27683890e-02]
 [8.38116374e-02 2.29542772e-02 5.14219033e-01 2.06391279e-01
  8.39935224e-02 7.79590178e-03 2.65087750e-03 9.15229968e-04
  1.41967067e-02 2.88655405e-02 1.13233103e-02 2.28826842e-02]
 [2.22968827e-02 1.03009063e-01 1.81789907e-01 4.21645056e-01
  1.82306942e-01 7.69315884e-03 2.59724583e-03 8.85196101e-04
  1.42375746e-02 2.90726565e-02 1.14290888e-02 2.30372285e-02]
 [2.21168949e-02 2.25255403e-02 1.22753492e-01 7.27173535e-02
  6.23568003e-01 5.85732157e-02 3.10792967e-03 1.19257

In [15]:
#开始进行迭代
init_array = np.array([1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_minor_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.09955516]
 [0.09448574]
 [0.08790447]
 [0.0754763 ]
 [0.09839578]
 [0.07809913]
 [0.07584602]
 [0.04764275]
 [0.06339027]
 [0.13458549]
 [0.06331583]
 [0.08130306]]
1 	 [[0.10995167]
 [0.10878901]
 [0.09100367]
 [0.07431285]
 [0.10619306]
 [0.06234986]
 [0.07005166]
 [0.03207826]
 [0.05352011]
 [0.15445404]
 [0.05256133]
 [0.08473448]]
2 	 [[0.1177141 ]
 [0.12032541]
 [0.09389186]
 [0.07504454]
 [0.11061889]
 [0.05013109]
 [0.06090605]
 [0.02487198]
 [0.04894523]
 [0.16143811]
 [0.04726994]
 [0.0888428 ]]
3 	 [[0.12337712]
 [0.12839372]
 [0.0964905 ]
 [0.07626443]
 [0.11299273]
 [0.04252881]
 [0.05158853]
 [0.02049386]
 [0.04704156]
 [0.16369526]
 [0.04490864]
 [0.09222483]]
4 	 [[0.1273197 ]
 [0.13372976]
 [0.09863001]
 [0.07747365]
 [0.11413752]
 [0.03781694]
 [0.0440473 ]
 [0.01722987]
 [0.04640812]
 [0.16450498]
 [0.04400885]
 [0.09469329]]
5 	 [[0.12997917]
 [0.13720917]
 [0.10027024]
 [0.07849152]
 [0.11461923]
 [0.03465428]
 [0.03852171]
 [0.01470145]
 [0.04632955]
 [0.1

In [16]:
minor_list = [0,1,2.5,4,5,6.5,8,9,-1.5,-3,-4,-5.5]
p_list1 = []

i = 0
for i in range(len(minor_list)):
    target_list = res[i]
    p_list1.append(target_list[0])
print(p_list1)

reflect_0 = minor_reflect([0])
print(reflect_0)
reflect_1 = minor_reflect([1,8])
print(reflect_1)
reflect_2 = minor_reflect([9])
print(reflect_2)
reflect_2_5 =minor_reflect([2.5,-5.5])
print(reflect_2_5)
reflect_4 = minor_reflect([4,-4])
print(reflect_4)
reflect_5 = minor_reflect([5,-3])
print(reflect_5)
reflect_6_5 = minor_reflect([6.5,-1.5])
print(reflect_6_5)

minor_list_new = [4.5,1,2,2.5,4,5,6.5]
p_list_new=[]
p_list_new.append(p_list1[0])
p_list_new.append(p_list1[1]+p_list1[6])
p_list_new.append(p_list1[7])
p_list_new.append(p_list1[2]+p_list1[11])
p_list_new.append(p_list1[3]+p_list1[10])
p_list_new.append(p_list1[4]+p_list1[9])
p_list_new.append(p_list1[5]+p_list1[8])

print(minor_list_new)
print(p_list_new)

minor_80 = np.random.choice(minor_list_new, 80, p=p_list_new)

[0.13517201299576093, 0.1452730371858419, 0.1040530515840962, 0.08102308414561081, 0.11386276656082654, 0.025962389708382563, 0.02417392922254218, 0.007634086351259011, 0.047432998134636986, 0.16966800990485653, 0.04482689919306106, 0.10091773501312769]
[0]
[1, 6]
[7]
[2, 11]
[3, 10]
[4, 9]
[5, 8]
[4.5, 1, 2, 2.5, 4, 5, 6.5]
[0.13517201299576093, 0.16944696640838408, 0.007634086351259011, 0.2049707865972239, 0.12584998333867187, 0.2835307764656831, 0.07339538784301955]


In [17]:
minor1 = CtoBm(minor_80[0:32])
minor2 = CtoEm(minor_80[32:48])
minor3 = CtoBm(minor_80[48:64])
minor4 = CtoBm(minor_80[64:80])

In [18]:
#Gmaj7
Gmaj7_list = [7,7,7,7,9,9,9,9,8.5,8.5,0,0,9,8.5,7,7]

#映射顺序 0,7,8.5,9
def Gmaj7_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 7:
            trans_vector.append(1)
        elif target == 8.5:
            trans_vector.append(2)
        elif target == 9:
            trans_vector.append(3)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [19]:
reflec_Gmaj7_list = Gmaj7_reflect(Gmaj7_list)

Gmaj7_array = np.zeros((4,4))
Gmaj7_array = markoving(Gmaj7_array,reflec_Gmaj7_list)
print(Gmaj7_array)

markov_Gmaj7 = normalize_matrix(Gmaj7_array)
print(markov_Gmaj7)
sum_rows(markov_Gmaj7)

[[1. 0. 0. 1.]
 [0. 4. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 2. 3.]]
[[0.5        0.         0.         0.5       ]
 [0.         0.8        0.         0.2       ]
 [0.33333333 0.33333333 0.33333333 0.        ]
 [0.         0.         0.4        0.6       ]]
[1.0, 1.0, 1.0, 1.0]


In [20]:
#邻接矩阵
adj_Gmaj7 = np.zeros((4,4))

adj_Gmaj7 = generate_adj(adj_Gmaj7,reflec_Gmaj7_list)
print(adj_Gmaj7)

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 1. 1.]]


In [21]:
k = 8
x = 0.8

i = 0
Iter_adj_Gmaj7 = 1
for i in range(k):
    Iter_adj_Gmaj7 = np.dot(adj_Gmaj7,Iter_adj_Gmaj7)

print(Iter_adj_Gmaj7)
Iter_adj_Gmaj7 = normalize_matrix(Iter_adj_Gmaj7)

markov_Gmaj7_final = x*markov_Gmaj7 + (1-x)*Iter_adj_Gmaj7
print(markov_Gmaj7_final)
sum_rows(markov_Gmaj7_final)

[[113. 112. 144. 180.]
 [112. 113. 144. 180.]
 [180. 180. 225. 288.]
 [144. 144. 180. 225.]]
[[0.44116576 0.04080146 0.05245902 0.46557377]
 [0.04080146 0.68116576 0.05245902 0.22557377]
 [0.30790378 0.30790378 0.31821306 0.06597938]
 [0.04155844 0.04155844 0.37194805 0.54493506]]
[1.0, 1.0, 1.0, 1.0]


In [22]:
#开始进行迭代
init_array = np.array([1/4,1/4,1/4,1/4]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_Gmaj7_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.20785736]
 [0.26785736]
 [0.19876979]
 [0.3255155 ]]
1 	 [[0.1773584 ]
 [0.26566603]
 [0.20928152]
 [0.34769404]]
2 	 [[0.16797221]
 [0.26708728]
 [0.21916086]
 [0.34577965]]
3 	 [[0.16685166]
 [0.27063474]
 [0.22117471]
 [0.34133889]]
4 	 [[0.16693757]
 [0.27344095]
 [0.22029112]
 [0.33933036]]
5 	 [[0.16673444]
 [0.27500042]
 [0.2194146 ]
 [0.33885054]]
6 	 [[0.16641863]
 [0.27576456]
 [0.21902837]
 [0.33878844]]
7 	 [[0.16618898]
 [0.27615068]
 [0.21890588]
 [0.33875446]]
8 	 [[0.16606429]
 [0.2763652 ]
 [0.21886248]
 [0.33870804]]
9 	 [[0.16600274]
 [0.27649093]
 [0.21883611]
 [0.33867021]]
10 	 [[0.16597103]
 [0.27656438]
 [0.21881702]
 [0.33864757]]
11 	 [[0.16595322]
 [0.2766063 ]
 [0.21880471]
 [0.33863578]]
12 	 [[0.16594279]
 [0.27662984]
 [0.21879767]
 [0.3386297 ]]
13 	 [[0.16593673]
 [0.27664304]
 [0.21879386]
 [0.33862638]]
14 	 [[0.16593328]
 [0.27665046]
 [0.21879178]
 [0.33862447]]
15 	 [[0.16593135]
 [0.27665466]
 [0.21879062]
 [0.33862337]]
16 	 [[0.16593026]

In [23]:
#映射顺序 0,7,8.5,9
Gmaj7_list = [0,7,8.5,9]
p_list2 = []

i = 0
for i in range(len(Gmaj7_list)):
    target_list = res[i]
    p_list2.append(target_list[0])
print(p_list2)

#主歌大调：K=3，x=0.8
Gmaj7_8 = np.random.choice(Gmaj7_list, 8, p=p_list2)
Gmaj7 = Gmaj7_8.tolist()

[0.16592885158540469, 0.27666013949507745, 0.2187890916183776, 0.3386219173011437]


In [24]:
#F7
F7_list = [7,7,7,7,9,7,7,7, 4.5,4.5,6,6,7,7,9,9]

#映射顺序 4.5,6,7,9
def F7_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 4.5:
            trans_vector.append(0)
        elif target == 6:
            trans_vector.append(1)
        elif target == 7:
            trans_vector.append(2)
        elif target == 9:
            trans_vector.append(3)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [25]:
reflec_F7_list = F7_reflect(F7_list)

F7_array = np.zeros((4,4))
F7_array = markoving(F7_array,reflec_F7_list)
print(F7_array)

markov_F7 = normalize_matrix(F7_array)
print(markov_F7)
sum_rows(markov_F7)

[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 0. 6. 2.]
 [0. 0. 1. 1.]]
[[0.5        0.5        0.         0.        ]
 [0.         0.5        0.5        0.        ]
 [0.11111111 0.         0.66666667 0.22222222]
 [0.         0.         0.5        0.5       ]]
[1.0, 1.0, 0.9999999999999999, 1.0]


In [26]:
#邻接矩阵
adj_F7 = np.zeros((4,4))

adj_F7 = generate_adj(adj_F7,reflec_F7_list)
print(adj_F7)

[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [27]:
k = 8
x = 0.8

i = 0
Iter_adj_F7 = 1
for i in range(k):
    Iter_adj_F7 = np.dot(adj_F7,Iter_adj_F7)

print(Iter_adj_F7)
Iter_adj_F7 = normalize_matrix(Iter_adj_F7)

markov_F7_final = x*markov_F7 + (1-x)*Iter_adj_F7
print(markov_F7_final)
sum_rows(markov_F7_final)

[[151. 115. 200. 150.]
 [200. 151. 265. 200.]
 [265. 200. 351. 265.]
 [200. 150. 265. 201.]]
[[0.44902597 0.43733766 0.06493506 0.0487013 ]
 [0.04901961 0.4370098  0.46495098 0.04901961]
 [0.13791757 0.03700278 0.5982732  0.22680645]
 [0.04901961 0.03676471 0.46495098 0.44926471]]
[1.0000000000000002, 0.9999999999999999, 0.9999999999999999, 1.0]


In [28]:
#开始进行迭代
init_array = np.array([1/4,1/4,1/4,1/4]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_F7_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.17124569]
 [0.23702874]
 [0.39827756]
 [0.19344802]]
1 	 [[0.15292504]
 [0.20032551]
 [0.44954923]
 [0.19720023]]
2 	 [[0.1501546 ]
 [0.17830866]
 [0.46371344]
 [0.2078233 ]]
3 	 [[0.15030558]
 [0.16839014]
 [0.46671006]
 [0.21459422]]
4 	 [[0.15063237]
 [0.1644815 ]
 [0.46704918]
 [0.21783696]]
5 	 [[0.15079323]
 [0.16304806]
 [0.46696367]
 [0.21919504]]
6 	 [[0.15084998]
 [0.16253875]
 [0.46688792]
 [0.21972335]]
7 	 [[0.15086594]
 [0.16235762]
 [0.46685512]
 [0.21992131]]
8 	 [[0.15086941]
 [0.16229151]
 [0.46684437]
 [0.21999471]]
9 	 [[0.15086984]
 [0.16226643]
 [0.46684154]
 [0.22002218]]
10 	 [[0.15086977]
 [0.16225657]
 [0.46684099]
 [0.22003267]]
11 	 [[0.15086969]
 [0.16225259]
 [0.46684095]
 [0.22003677]]
12 	 [[0.15086965]
 [0.16225097]
 [0.46684098]
 [0.2200384 ]]
13 	 [[0.15086964]
 [0.1622503 ]
 [0.466841  ]
 [0.22003906]]
14 	 [[0.15086963]
 [0.16225003]
 [0.466841  ]
 [0.22003933]]
15 	 [[0.15086963]
 [0.16224992]
 [0.46684101]
 [0.22003944]]
16 	 [[0.15086963]

In [29]:
#映射顺序 4.5,6,7,9
F7_list = [4.5,6,7,9]
p_list3 = []

i = 0
for i in range(len(F7_list)):
    target_list = res[i]
    p_list3.append(target_list[0])
print(p_list3)

#主歌大调：K=3，x=0.8
F7_8 = np.random.choice(F7_list, 8, p=p_list3)
F7 = F7_8.tolist()

[0.1508696343092095, 0.16224984830044853, 0.4668410064825114, 0.2200395109078287]


In [30]:
seq = minor1 + minor2 + minor3 + Gmaj7 + F7 + minor4
print(seq)

[9, 7, 9, 11.5, 11.5, 9, 9, 9, 11, 11, 13, 9, 10, 9, 9, 10, 11, 11.5, 13, 11.5, 10, 7, 11, 11.5, 9, 11, 10, 7, 11.5, 7, 9, 13, 6, 6.5, 5, 7, 3, 6.5, 3, 6, 7, 9, 7, 7, 5, 5, 6, 7, 13, 9, 7, 13, 11.5, 10, 13, 11, 13, 11, 7, 7, 11.5, 11.5, 11.5, 11.5, 9.0, 8.5, 9.0, 7.0, 9.0, 0.0, 8.5, 8.5, 7.0, 7.0, 7.0, 4.5, 4.5, 7.0, 9.0, 7.0, 10, 13, 10, 11.5, 7, 9, 10, 11, 9, 11, 7, 11.5, 9, 11.5, 7, 13]


In [31]:
def post_process(vector):
    vector[6] = 0
    vector[7] = 0
    vector[8] = 0
    vector[9] = 0
    vector[22] = 0
    vector[23] = 0
    vector[24] = 0
    
    vector[38] = 0
    vector[39] = 0
    vector[40] = 0
    
    vector[47] = 0
    vector[48] = 0
    

    vector[53] = 0
    vector[54] = 0
        
    
    for i in range(len(vector)):
        if vector[i] == 0:
            vector[i] = vector[i-1]
    return vector

seq = post_process(seq)

In [32]:
import mido
from mido import Message, MidiFile, MidiTrack

In [33]:
import math

def map_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 4:
        result = 6
    elif num == 4.5:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result   


def map2_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 3.5:
        result = 6
    elif num == 4:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result 
        
        
def toMidi(vector):
    
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target > 0:
            base = 59   #基数是59
            int_part = math.floor(target)     #得到target的整数部分
            times = math.floor(int_part/7)    #整数部分是由多少个7组成的
            base += times*12

            remain = target - times*7        #得到剩余部分
            base += map_remain(remain)
            trans_vector.append(base)
#         elif target == 0:
#             last = trans_vector[len(trans_vector)]
#             trans_vector.append(last)
        else:  #target < 0
            base = 60   #基数是60
            target = abs(target)
            int_part = math.floor(target)
            times = math.floor(int_part/7)
            base -= times*12
            
            remain = target - times*7
            base -= map2_remain(remain)
            trans_vector.append(base)
    return trans_vector

toMidi(seq)

[77,
 74,
 74,
 76,
 76,
 77,
 77,
 77,
 77,
 77,
 78,
 76,
 71,
 78,
 74,
 76,
 71,
 74,
 74,
 77,
 78,
 78,
 78,
 78,
 78,
 78,
 78,
 74,
 71,
 81,
 78,
 71,
 70,
 70,
 71,
 71,
 64,
 67,
 67,
 67,
 67,
 71,
 71,
 69,
 67,
 70,
 71,
 71,
 71,
 78,
 71,
 76,
 81,
 81,
 81,
 74,
 71,
 74,
 77,
 78,
 78,
 71,
 78,
 78,
 73,
 74,
 71,
 74,
 71,
 74,
 73,
 74,
 71,
 74,
 71,
 74,
 71,
 71,
 71,
 71,
 76,
 74,
 78,
 78,
 78,
 78,
 81,
 81,
 77,
 78,
 81,
 78,
 74,
 74,
 74,
 78]

In [34]:
mid = MidiFile()       #给自己的文件定的.mid后缀
track = MidiTrack()    #定义声部，一个MidoTrack()就是一个声部

In [35]:
def beat(time):            #与mido的拍子互换  
    time /= 60 * 1000  
    time = 1/time  
    return time  

def yin(yin,pai,qian=0,unit = track, liang=64,qi=2): #yin是音，pai是指时间（节拍），
    if type(yin)== str:               #qian是是音前多少拍
        yin = num(yin)                #liang是音量

    unit.append(Message('program_change',channel=0,program=qi,time=0))
    unit.append(Message('note_on',note=yin,velocity=liang,time=qian,channel=0))
    unit.append(Message('note_off',note=yin,velocity=liang,time=int(beat(pai)),channel=0))

In [36]:
def find_nearest(num, vector):
    result = num
    mark = 100
    length = len(vector)
    for i in range(length):
        instance = abs(num - vector[i])
        if mark > instance:
            mark = instance
            result = vector[i]
        else:
            continue
    return result

In [37]:
#后处理

fuge_sequence = seq
midi_sequence = toMidi(fuge_sequence)

bules_list = [-1,2,3,4,4.5,6,6.5,7,9,10,11,11.5,13]
midi_bules_list = toMidi(bules_list)
i = 0 
for i in range(len(midi_sequence)):
    target = fuge_sequence[i]
    midi_target = midi_sequence[i]
    if target>11.5:
        midi_target -= 12
    elif target < 2:
        midi_target += 12
    
    if midi_target in midi_bules_list:
        yin(midi_target,120, 0,track,80,2)
    else:
        midi_target = find_nearest(midi_target,midi_bules_list)
        yin(midi_target,120, 0,track,80,2)    

In [38]:
mid.tracks.append(track)
mid.save('C:\\Users\\Administrator\\Desktop\\2020Summer\\blues4_2.mid')