In [1]:
import numpy as np

In [2]:
#Em Am 与 C 之间的转换
def AmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-5.5)
        elif target == 2:
            trans_vector.append(-4)
        elif target == 3:
            trans_vector.append(-3)
        elif target == 4:
            trans_vector.append(-2.5)
        elif target == 5:
            trans_vector.append(-1.5)
        elif target == 6:
            trans_vector.append(1)
        elif target == 7:
            trans_vector.append(2)
        elif target == 8:
            trans_vector.append(2.5)
        elif target == 10:
            trans_vector.append(5)
        elif target == -1:
            trans_vector.append(-6)
        elif target == -2:
            trans_vector.append(-7)
        elif target == -2.5:
            trans_vector.append(-8)
        elif target == -3:
            trans_vector.append(-8.5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoAm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -5.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-3)
        elif target == -7:
            trans_vector.append(-2)
        elif target == -4:
            trans_vector.append(2)
        elif target == -3:
            trans_vector.append(3)
        elif target == -2.5:
            trans_vector.append(4)
        elif target == 2.5:
            trans_vector.append(8)
        elif target == -1.5:
            trans_vector.append(5)
        elif target == -6:
            trans_vector.append(-1)
        elif target == 1:
            trans_vector.append(6)
        elif target == 5:
            trans_vector.append(10)
        elif target == -8:
            trans_vector.append(-2.5)
        elif target == 2:
            trans_vector.append(7)
        elif target == 9.5:
            trans_vector.append(8)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def DmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(1)
        elif target == 3:
            trans_vector.append(2)
        elif target == 4:
            trans_vector.append(2.5)
        elif target == -2:
            trans_vector.append(-3)
        elif target == 1:
            trans_vector.append(-1.5)
        elif target == 11:
            trans_vector.append(9.5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoDm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(2)
        elif target == 2:
            trans_vector.append(3)
        elif target == 2.5:
            trans_vector.append(4)
        elif target == -3:
            trans_vector.append(-2)
        elif target == 5:
            trans_vector.append(6)
        elif target == -8:
            trans_vector.append(-6.5)
        elif target == -1.5:
            trans_vector.append(1)
        elif target == 9.5:
            trans_vector.append(11)
        elif target == -5.5:
            trans_vector.append(-4)
        elif target == -7:
            trans_vector.append(-6)
        elif target == -6:
            trans_vector.append(-5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [3]:
def count_number(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

In [4]:
AmtoC_list = AmtoC([3,3,3,3, 6,6, 7,7, 8,8, 7,7, 6,6,6,6,
                    3,3,3,3, 3,3, 0,0,
                    3,3,3,3, 6,6, 7,7, 8,8, 7,7, 6,6,6,6,
                    -2,-2,-2,-2,-2,-2,0,0,
                    1,1, 1,1, -1,-1,-2,-2, 3,3,3,3,
                    3,3,3,3,3,3,0,0,
                    3,3, 3,3, 6,6, 7,7, 8,8,7,7,6,6,6,6,
                    -2,-2,-2,-2,-2,-2,0,0])
len(AmtoC_list)

92

In [5]:
DmtoC_list = DmtoC([4,4,4,4,3,3,2,2,
                    4,4,2,2,
                    4,4,4,4,
                    2,2,3,3,4,4,4,4,
                    4,4,2,2])

In [6]:
major_list = AmtoC_list+DmtoC_list

In [7]:
print(major_list)
count_number(major_list)

[-3, -3, -3, -3, 1, 1, 2, 2, 2.5, 2.5, 2, 2, 1, 1, 1, 1, -3, -3, -3, -3, -3, -3, 0, 0, -3, -3, -3, -3, 1, 1, 2, 2, 2.5, 2.5, 2, 2, 1, 1, 1, 1, -7, -7, -7, -7, -7, -7, 0, 0, -5.5, -5.5, -5.5, -5.5, -6, -6, -7, -7, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, 0, 0, -3, -3, -3, -3, 1, 1, 2, 2, 2.5, 2.5, 2, 2, 1, 1, 1, 1, -7, -7, -7, -7, -7, -7, 0, 0, 2.5, 2.5, 2.5, 2.5, 2, 2, 1, 1, 2.5, 2.5, 1, 1, 2.5, 2.5, 2.5, 2.5, 1, 1, 2, 2, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 1, 1]


{0: 8, 1: 26, 2: 16, 2.5: 22, -7: 14, -6: 2, -5.5: 4, -3: 28}

In [8]:
#映射顺序 0,1,2,2.5,-3,-5.5,-6,-7
def major_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 2:
            trans_vector.append(2)
        elif target == 2.5:
            trans_vector.append(3)
        elif target == -3:
            trans_vector.append(4)
        elif target == -5.5:
            trans_vector.append(5)
        elif target == -6:
            trans_vector.append(6)
        elif target == -7:
            trans_vector.append(7)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [9]:
reflect_major_list = major_reflect(major_list)
print(reflect_major_list)
len(reflect_major_list)

[4, 4, 4, 4, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1, 1, 7, 7, 7, 7, 7, 7, 0, 0, 5, 5, 5, 5, 6, 6, 7, 7, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1, 1, 7, 7, 7, 7, 7, 7, 0, 0, 3, 3, 3, 3, 2, 2, 1, 1, 3, 3, 1, 1, 3, 3, 3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1]


120

In [10]:
def markoving(darray, vector):
    num = len(vector)
    for i in range(num-1):   #最后一个不用考虑
        row = vector[i]
        column = vector[i+1]
        darray[row][column] += 1
    return darray

In [11]:
major_array = np.zeros((8,8))
#先处理Am1和旋部分：
Am1 = reflect_major_list[0:8]
major_array = markoving(major_array,Am1)
# print(major_array)

#先处理Am2和旋部分：
Am2 = reflect_major_list[8:16]
major_array = markoving(major_array,Am2)
# print(major_array)

#先处理Am3和旋部分：
Am3 = reflect_major_list[16:24]
major_array = markoving(major_array,Am3)
# print(major_array)

#先处理Am4和旋部分：
Am4 = reflect_major_list[24:32]
major_array = markoving(major_array,Am4)
# print(major_array)

#先处理Am5和旋部分：
Am5 = reflect_major_list[32:40]
major_array = markoving(major_array,Am5)
# print(major_array)

#先处理Am6和旋部分：
Am6 = reflect_major_list[40:48]
major_array = markoving(major_array,Am6)
# print(major_array)

#先处理Am7和旋部分：
Am7 = reflect_major_list[48:56]
major_array = markoving(major_array,Am7)
# print(major_array)

#先处理Am8和旋部分：
Am8 = reflect_major_list[56:60]
major_array = markoving(major_array,Am8)
# print(major_array)

#先处理Am9和旋部分：
Am9 = reflect_major_list[60:68]
major_array = markoving(major_array,Am9)
# print(major_array)

#先处理Am10和旋部分：
Am10 = reflect_major_list[68:76]
major_array = markoving(major_array,Am10)
# print(major_array)

#先处理Am11和旋部分：
Am11 = reflect_major_list[76:84]
major_array = markoving(major_array,Am11)
# print(major_array)

#先处理Am12和旋部分：
Am12 = reflect_major_list[84:92]
major_array = markoving(major_array,Am12)
print(major_array)

#Dm1
Dm1 = reflect_major_list[92:100]
major_array = markoving(major_array,Dm1)
# print(major_array)

#Dm2
Dm2 = reflect_major_list[100:104]
major_array = markoving(major_array,Dm2)
# print(major_array)

#Dm3
Dm3 = reflect_major_list[104:108]
major_array = markoving(major_array,Dm3)
# print(major_array)

#Dm4
Dm4 = reflect_major_list[108:116]
major_array = markoving(major_array,Dm4)
# print(major_array)

#Dm5
Dm5 = reflect_major_list[116:120]
major_array = markoving(major_array,Dm5)
print(major_array)

[[ 4.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 12.  3.  0.  0.  0.  0.  0.]
 [ 0.  3.  6.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  3.  0.  0.  0.  0.]
 [ 2.  3.  0.  0. 22.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  3.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.]
 [ 2.  0.  0.  0.  0.  0.  0. 11.]]
[[ 4.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 16.  4.  0.  0.  0.  0.  0.]
 [ 0.  4.  8.  1.  0.  0.  0.  0.]
 [ 0.  2.  4. 14.  0.  0.  0.  0.]
 [ 2.  3.  0.  0. 22.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  3.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.]
 [ 2.  0.  0.  0.  0.  0.  0. 11.]]


In [12]:
def normalize_matrix(matrix):
    mat_size = matrix.shape[0]
    init_array = np.zeros((mat_size,mat_size))
    sum_row_list=[]
    for i in range(mat_size):
        count=0
        for j in range(mat_size):
            count+=matrix[i][j]
        sum_row_list.append(count)
    for k in range(mat_size):
        if sum_row_list[k] == 0:
            init_array[k][k] = 0
        else:
            init_array[k][k] = 1/sum_row_list[k]
    result = np.dot(init_array,matrix)
    
    return result

def sum_rows(matrix):
    sum_row_list1=[]
    for ii in range(len(matrix)):
        count=0
        for jj in range(len(matrix[ii])):
            count+=matrix[ii][jj]
        sum_row_list1.append(count)
    print(sum_row_list1)

In [13]:
markov_major = normalize_matrix(major_array)
print(markov_major)
sum_rows(markov_major)

[[1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.8        0.2        0.         0.         0.
  0.         0.        ]
 [0.         0.30769231 0.61538462 0.07692308 0.         0.
  0.         0.        ]
 [0.         0.1        0.2        0.7        0.         0.
  0.         0.        ]
 [0.07407407 0.11111111 0.         0.         0.81481481 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.75
  0.25       0.        ]
 [0.         0.         0.         0.         0.         0.
  0.5        0.5       ]
 [0.15384615 0.         0.         0.         0.         0.
  0.         0.84615385]]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [14]:
#第一行，调一下参数
x = 0.8
modify_line = np.array([1/8,1/8,1/8,1/8,1/8,1/8,1/8,1/8])
line1 = markov_major[0]
line1 = x*line1 + (1-x)*modify_line
markov_major[[0],:] = line1
print(markov_major)
sum_rows(markov_major)

[[0.825      0.025      0.025      0.025      0.025      0.025
  0.025      0.025     ]
 [0.         0.8        0.2        0.         0.         0.
  0.         0.        ]
 [0.         0.30769231 0.61538462 0.07692308 0.         0.
  0.         0.        ]
 [0.         0.1        0.2        0.7        0.         0.
  0.         0.        ]
 [0.07407407 0.11111111 0.         0.         0.81481481 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.75
  0.25       0.        ]
 [0.         0.         0.         0.         0.         0.
  0.5        0.5       ]
 [0.15384615 0.         0.         0.         0.         0.
  0.         0.84615385]]
[1.0000000000000002, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [15]:
#邻接矩阵

def generate_adj(darray, vector):
    num = len(vector)
    for i in range(num-1):
        row = vector[i]
        column = vector[i+1]
        darray[row][column] = 1
    return darray

In [16]:
adj_major = np.zeros((8,8))
# #先处理F1和旋部分：
# adj_major = generate_adj(adj_major,F1)
#先处理Am1和旋部分：
adj_major = generate_adj(adj_major,Am1)

#先处理Am2和旋部分：
adj_major = generate_adj(adj_major,Am2)

#先处理Am3和旋部分：
adj_major = generate_adj(adj_major,Am3)

#先处理Am4和旋部分：
adj_major = generate_adj(adj_major,Am4)

#先处理Am5和旋部分：
adj_major = generate_adj(adj_major,Am5)

#先处理Am6和旋部分：
adj_major = generate_adj(adj_major,Am6)

#先处理Am7和旋部分：
adj_major = generate_adj(adj_major,Am7)

#先处理Am8和旋部分：
adj_major = generate_adj(adj_major,Am8)

#先处理Am9和旋部分：
adj_major = generate_adj(adj_major,Am9)

#先处理Am10和旋部分：
adj_major = generate_adj(adj_major,Am10)

#先处理Am11和旋部分：
adj_major = generate_adj(adj_major,Am11)

#先处理Am12和旋部分：
adj_major = generate_adj(adj_major,Am12)

#Dm1
adj_major = generate_adj(adj_major,Dm1)

#Dm2
adj_major = generate_adj(adj_major,Dm2)

#Dm3
adj_major = generate_adj(adj_major,Dm3)

#Dm4
adj_major = generate_adj(adj_major,Dm4)

#Dm5
adj_major = generate_adj(adj_major,Dm5)

print(adj_major)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
#邻接矩阵调参数
k=1
x = 0.8

i = 0
Iter_adj_major = 1
for i in range(k):
    Iter_adj_major = np.dot(adj_major,Iter_adj_major)
    
Iter_adj_major = normalize_matrix(Iter_adj_major)
# print(Iter_adj_major)


x = 0.8
modify_line = np.array([1/8,1/8,1/8,1/8,1/8,1/8,1/8,1/8])
line1 = Iter_adj_major[0]
line1 = x*line1 + (1-x)*modify_line
Iter_adj_major[[0],:] = line1
# print(Iter_adj_major)


markov_major_final = x*markov_major + (1-x)*Iter_adj_major
sum_rows(markov_major_final)
print(markov_major_final)

[1.0000000000000002, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[[0.825      0.025      0.025      0.025      0.025      0.025
  0.025      0.025     ]
 [0.         0.74       0.26       0.         0.         0.
  0.         0.        ]
 [0.         0.31282051 0.55897436 0.12820513 0.         0.
  0.         0.        ]
 [0.         0.14666667 0.22666667 0.62666667 0.         0.
  0.         0.        ]
 [0.12592593 0.15555556 0.         0.         0.71851852 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.7
  0.3        0.        ]
 [0.         0.         0.         0.         0.         0.
  0.5        0.5       ]
 [0.22307692 0.         0.         0.         0.         0.
  0.         0.77692308]]


In [18]:
#开始进行迭代
init_array = np.array([1/8,1/8,1/8,1/8,1/8,1/8,1/8,1/8]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(100):
    res = np.dot(markov_major_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.14675036]
 [0.17250534]
 [0.13383013]
 [0.09748397]
 [0.09293981]
 [0.090625  ]
 [0.103125  ]
 [0.16274038]]
1 	 [[0.1690762 ]
 [0.20194248]
 [0.14542413]
 [0.08191642]
 [0.07044774]
 [0.06710626]
 [0.08241876]
 [0.18166802]]
2 	 [[0.188885  ]
 [0.22212893]
 [0.15658803]
 [0.07420532]
 [0.05484491]
 [0.05120129]
 [0.06556816]
 [0.18657836]]
3 	 [[0.20435785]
 [0.23749636]
 [0.16682421]
 [0.07129951]
 [0.04412921]
 [0.04056303]
 [0.05286659]
 [0.18246324]]
4 	 [[0.21485558]
 [0.25036409]
 [0.17626968]
 [0.07117769]
 [0.0368166 ]
 [0.03350306]
 [0.04371115]
 [0.17330214]]
5 	 [[0.22055172]
 [0.26194801]
 [0.1851299 ]
 [0.07257475]
 [0.0318248 ]
 [0.02882353]
 [0.03727788]
 [0.1618694 ]]
6 	 [[0.22207207]
 [0.27286257]
 [0.19355342]
 [0.07472857]
 [0.0283805 ]
 [0.02569027]
 [0.0327998 ]
 [0.14991281]]
7 	 [[0.22022538]
 [0.28339252]
 [0.20162594]
 [0.07719625]
 [0.02594372]
 [0.02353499]
 [0.02965878]
 [0.13842242]]
8 	 [[0.21583178]
 [0.29364664]
 [0.20938924]
 [0.07973143]
 [0.

In [19]:
major_list = [0,1,2,2.5,-3,-5.5,-6,-7]
p_list1 = []

i = 0
for i in range(len(major_list)):
    target_list = res[i]
    p_list1.append(target_list[0])
print(p_list1)

# i = 0
# count = 0
# for i in range(len(p_list)):
#     count += p_list[i]
# print(count)
# 主歌大调：K=3，x=0.8
major_60 = np.random.choice(major_list, 60, p=p_list1)
# major_120 = np.random.choice(major_list, 120, p=p_list1)

[0.0021178912607017508, 0.5077366573377229, 0.363481252249997, 0.12490861742163459, 0.0002289313402279663, 0.0002119597975701306, 0.0002590830547933474, 0.001055607537358945]


In [20]:
#Am1
major1 = CtoAm(major_60[0:4])
major2 = CtoAm(major_60[4:8])
major3 = CtoDm(major_60[8:12])
major4 = CtoAm(major_60[12:16])

major5 = CtoAm(major_60[16:20])
major6 = CtoAm(major_60[20:24])
major7 = CtoDm(major_60[24:26])
major8 = [3,3]
major9 = CtoAm(major_60[26:30])

major10 = CtoAm(major_60[30:34])
major11 = CtoDm(major_60[34:36])
major12 = CtoAm(major_60[36:38])
major13 = CtoDm(major_60[38:42])
major14 = CtoAm(major_60[42:46])

major15 = CtoAm(major_60[46:50])
major16 = CtoAm(major_60[50:54])
major17 = CtoDm(major_60[54:56])
major18 = [3,3]
major19 = CtoAm(major_60[56:60])


# major1 = CtoAm(major_120[0:8])
# major2 = CtoAm(major_120[8:16])
# major3 = CtoDm(major_120[16:24])
# major4 = CtoAm(major_120[24:32])

# major5 = CtoAm(major_120[32:40])
# major6 = CtoAm(major_120[40:48])
# major7 = CtoDm(major_120[48:52])
# major8 = [3,3,3,3]
# major9 = CtoAm(major_120[52:60])

# major10 = CtoAm(major_120[60:68])
# major11 = CtoDm(major_120[68:72])
# major12 = CtoAm(major_120[72:76])
# major13 = CtoDm(major_120[76:84])
# major14 = CtoAm(major_120[84:92])

# major15 = CtoAm(major_120[92:100])
# major16 = CtoAm(major_120[100:108])
# major17 = CtoDm(major_120[108:112])
# major18 = [3,3,3,3]
# major19 = CtoAm(major_120[112:120])

In [21]:
seq = major1 + major2 +major3 +major4 +major5 +major6 +major7 +major8 +major9 +major10 +major11 +major12 +major13 +major14 +major15 +major16 +major17 +major18 +[-2,-2,-2,-2]
print(seq)

[6, 6, 8, 6, 6, 8, 6, 6, 2, 3, 3, 2, 6, 6, 7, 6, 6, 8, 6, 6, 6, 7, 6, 6, 2, 2, 3, 3, 8, 7, 6, 6, 7, 6, 6, 8, 3, 3, 6, 6, 3, 4, 2, 3, 6, 8, 6, 7, 7, 6, 8, 6, 6, 8, 6, 6, 3, 3, 3, 3, -2, -2, -2, -2]


In [22]:
def post_process(vector):
    length = len(vector)
    for i in range(length):
        target = vector[i]
        if target == 0:
            if i == 0:
                vector[0] = vector[1]
            else:
                vector[i] = vector[i-1]
        vector[13] = vector[12]
        vector[14] = vector[12]
        vector[15] = vector[12]
        
        vector[29] = vector[28]
        vector[30] = vector[28]
        vector[31] = vector[28]
        
        vector[45] = vector[44]
        vector[46] = vector[44]
        vector[47] = vector[44]
        
        vector[16:24] = vector[0:8]
        vector[48:56] = vector[0:8]
        
#         vector[61] = vector[60]
#         vector[62] = vector[60]
#         vector[63] = vector[60]

#         vector[25] = vector[24]
#         vector[26] = vector[24]
#         vector[27] = vector[24]
#         vector[28] = vector[24]
#         vector[29] = vector[24]
#         vector[30] = vector[24]
#         vector[31] = vector[24]
        
#         vector[57] = vector[56]
#         vector[58] = vector[56]
#         vector[59] = vector[56]
#         vector[60] = vector[56]
#         vector[61] = vector[56]
#         vector[62] = vector[56]
#         vector[63] = vector[56]
        
#         vector[89] = vector[88]
#         vector[90] = vector[88]
#         vector[91] = vector[88]
#         vector[92] = vector[88]
#         vector[93] = vector[88]
#         vector[94] = vector[88]
#         vector[95] = vector[88]
        
#         vector[121] = vector[120]
#         vector[122] = vector[120]
#         vector[123] = vector[120]
#         vector[124] = vector[120]
#         vector[125] = vector[120]
#         vector[126] = vector[120]
#         vector[127] = vector[120]

    return vector

In [23]:
final_seq = post_process(seq)
len(final_seq)

64

In [24]:
#间奏
jAm1 = AmtoC([-2,-2,-2,-2,-1,-1,1,1])
jDm1 = DmtoC([2,2,4,4])
jAm2 = AmtoC([3,3,3,3])
jDm2 = DmtoC([-2,-2,-2,-2,1,1,-2,-2])
jAm3 = AmtoC([-1,-1,-1,-1,-2.5,-2.5,-2.5,-2.5])
jAm4 = AmtoC([-2,3,6,6,6,6,7,7,8,8,6,6,10,10,10,10])
jDm3 = DmtoC([1,1,1,1,1,1,1,1])
jAm5 = AmtoC([8,8,7,7,6,6,6,6])
jianzou_list = jAm1 + jDm1 +jAm2+jDm2+jAm3+jAm4+jDm3+jAm5
count_number(jianzou_list)

{1: 12, 2.5: 6, 2: 4, 5: 4, -8: 4, -7: 5, -6: 6, -5.5: 2, -3: 11, -1.5: 10}

In [25]:
#映射顺序 1,2,2.5,5,-1.5,-3,-5.5,-6,-7,-8
def jianzou_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(1)
        elif target == 2.5:
            trans_vector.append(2)
        elif target == 5:
            trans_vector.append(3)
        elif target == -1.5:
            trans_vector.append(4)
        elif target == -3:
            trans_vector.append(5)
        elif target == -5.5:
            trans_vector.append(6)
        elif target == -6:
            trans_vector.append(7)
        elif target == -7:
            trans_vector.append(8)
        elif target == -8:
            trans_vector.append(9)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [26]:
jianzou_array = np.zeros((10,10))

jianzou_array = markoving(jianzou_array,jianzou_reflect(jAm1))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jDm1))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jAm2))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jDm2))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jAm3))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jAm4))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jDm3))
jianzou_array = markoving(jianzou_array,jianzou_reflect(jAm5))

print(jianzou_array)

[[8. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 2. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 4. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 1. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]]


In [27]:
markov_jianzou = normalize_matrix(jianzou_array)
print(markov_jianzou)

[[0.72727273 0.09090909 0.09090909 0.09090909 0.         0.
  0.         0.         0.         0.        ]
 [0.25       0.5        0.25       0.         0.         0.
  0.         0.         0.         0.        ]
 [0.2        0.2        0.6        0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.88888889 0.11111111
  0.         0.         0.         0.        ]
 [0.11111111 0.         0.         0.         0.11111111 0.77777778
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.16666667 0.66666667 0.         0.16666667]
 [0.         0.         0.         0.         0.         0.2
  0.         0.2        0.6        0.        ]
 [0.         0.     

In [28]:
#第四行为空行，调一下参数
x= 0.8
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line4 = markov_jianzou[3]
line4 =x*line4 + (1-x)*modify_line
markov_jianzou[[3],:] = line4
# print(markov_major)
# sum_rows(markov_major)

#第7行为空行，调一下参数
x= 0.8
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line7 = markov_jianzou[6]
line7 =x*line7 + (1-x)*modify_line
markov_jianzou[[6],:] = line7
# print(markov_major)
# sum_rows(markov_major)

#第10行为空行，调一下参数
x= 0.8
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line10 = markov_jianzou[9]
line10 =x*line10 + (1-x)*modify_line
markov_jianzou[[9],:] = line10
print(markov_jianzou)
sum_rows(markov_jianzou)

[[0.72727273 0.09090909 0.09090909 0.09090909 0.         0.
  0.         0.         0.         0.        ]
 [0.25       0.5        0.25       0.         0.         0.
  0.         0.         0.         0.        ]
 [0.2        0.2        0.6        0.         0.         0.
  0.         0.         0.         0.        ]
 [0.02       0.02       0.02       0.82       0.02       0.02
  0.02       0.02       0.02       0.02      ]
 [0.         0.         0.         0.         0.88888889 0.11111111
  0.         0.         0.         0.        ]
 [0.11111111 0.         0.         0.         0.11111111 0.77777778
  0.         0.         0.         0.        ]
 [0.02       0.02       0.02       0.02       0.02       0.02
  0.82       0.02       0.02       0.02      ]
 [0.         0.         0.         0.         0.         0.
  0.16666667 0.66666667 0.         0.16666667]
 [0.         0.         0.         0.         0.         0.2
  0.         0.2        0.6        0.        ]
 [0.02       0.0

In [29]:
#邻接矩阵
adj_banzou = np.zeros((10,10))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jAm1))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jDm1))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jAm2))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jDm2))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jAm3))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jAm4))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jDm3))
adj_banzou = generate_adj(adj_banzou,jianzou_reflect(jAm5))

print(adj_banzou)

[[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [30]:
#邻接矩阵调参数
k=4
x = 0.8

i = 0
Iter_adj_banzou = 1
for i in range(k):
    Iter_adj_banzou = np.dot(adj_banzou,Iter_adj_banzou)

Iter_adj_banzou = normalize_matrix(Iter_adj_banzou)


#第四行为空行，调一下参数
x= 0.8
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line4 = markov_jianzou[3]
line4 =x*line4 + (1-x)*modify_line
markov_jianzou[[3],:] = line4
# print(markov_major)
# sum_rows(markov_major)

#第7行为空行，调一下参数
x= 0.8
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line7 = markov_jianzou[6]
line7 =x*line7 + (1-x)*modify_line
markov_jianzou[[6],:] = line7
# print(markov_major)
# sum_rows(markov_major)

#第10行为空行，调一下参数
x= 0.8
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line10 = markov_jianzou[9]
line10 =x*line10 + (1-x)*modify_line
markov_jianzou[[9],:] = line10
print(markov_jianzou)
sum_rows(markov_jianzou)

[[0.72727273 0.09090909 0.09090909 0.09090909 0.         0.
  0.         0.         0.         0.        ]
 [0.25       0.5        0.25       0.         0.         0.
  0.         0.         0.         0.        ]
 [0.2        0.2        0.6        0.         0.         0.
  0.         0.         0.         0.        ]
 [0.036      0.036      0.036      0.676      0.036      0.036
  0.036      0.036      0.036      0.036     ]
 [0.         0.         0.         0.         0.88888889 0.11111111
  0.         0.         0.         0.        ]
 [0.11111111 0.         0.         0.         0.11111111 0.77777778
  0.         0.         0.         0.        ]
 [0.036      0.036      0.036      0.036      0.036      0.036
  0.676      0.036      0.036      0.036     ]
 [0.         0.         0.         0.         0.         0.
  0.16666667 0.66666667 0.         0.16666667]
 [0.         0.         0.         0.         0.         0.2
  0.         0.2        0.6        0.        ]
 [0.036      0

In [31]:
#开始进行迭代
init_array = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_jianzou.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.13963838]
 [0.08989091]
 [0.10489091]
 [0.08389091]
 [0.1108    ]
 [0.11968889]
 [0.09146667]
 [0.09746667]
 [0.0708    ]
 [0.09146667]]
1 	 [[0.16791054]
 [0.08822371]
 [0.10770734]
 [0.07599025]
 [0.12139333]
 [0.12916814]
 [0.08438878]
 [0.08874345]
 [0.05208567]
 [0.08438878]]
2 	 [[0.18887781]
 [0.08972956]
 [0.11075657]
 [0.07271   ]
 [0.13106884]
 [0.13318103]
 [0.07761104]
 [0.07839108]
 [0.04006305]
 [0.07761104]]
3 	 [[0.20495283]
 [0.09239236]
 [0.1142626 ]
 [0.07191066]
 [0.13950908]
 [0.13436662]
 [0.0709418 ]
 [0.06847888]
 [0.03224338]
 [0.0709418 ]]
4 	 [[0.21763343]
 [0.09537737]
 [0.11798432]
 [0.07235149]
 [0.14663429]
 [0.13415365]
 [0.06451249]
 [0.05979786]
 [0.02704262]
 [0.06451249]]
5 	 [[0.22787558]
 [0.09831996]
 [0.12166934]
 [0.07333937]
 [0.1524971 ]
 [0.1332925 ]
 [0.05850386]
 [0.05252332]
 [0.02347513]
 [0.05850386]]
6 	 [[0.23630432]
 [0.1010623 ]
 [0.12515005]
 [0.07450565]
 [0.15721575]
 [0.13216359]
 [0.05304885]
 [0.04656306]
 [0.02093757]


In [32]:
jianzou_list = [1,2,2.5,5,-1.5,-3,-5.5,-6,-7,-8]
p_list4 = []

i = 0
for i in range(len(jianzou_list)):
    target_list = res[i]
    p_list4.append(target_list[0])
print(p_list4)

jianzou_30 = np.random.choice(jianzou_list,30, p=p_list4)

[0.2897495653260017, 0.124224470155557, 0.1552548294425396, 0.08634128506836292, 0.15469169713437855, 0.11004643057161115, 0.023160048342468053, 0.021447283350212953, 0.011924342266400843, 0.02316004834246805]


In [33]:
jianzou_seq = CtoAm(jianzou_30[0:4]) + CtoDm(jianzou_30[4:6]) + CtoAm(jianzou_30[6:8]) + CtoDm(jianzou_30[8:12]) + CtoAm(jianzou_30[12:16])+ CtoAm(jianzou_30[16:24]) + CtoDm(jianzou_30[24:26]) + [5,7] + [6,6,6,6]
print(jianzou_seq)
len(jianzou_seq)

[7, 8, 8, 8, 6, 4, 10, 7, 2, 2, 2, 1, 3, 10, 6, 10, 6, 7, 1, 10, 5, 6, 7, 10, 4, -2, 5, 7, 6, 6, 6, 6]


32

In [34]:
import mido
from mido import Message, MidiFile, MidiTrack

In [35]:
import math

def map_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 4:
        result = 6
    elif num == 4.5:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result   


def map2_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 3.5:
        result = 6
    elif num == 4:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result 
        
        
def toMidi(vector):
    
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target > 0:
            base = 59   #基数是59
            int_part = math.floor(target)     #得到target的整数部分
            times = math.floor(int_part/7)    #整数部分是由多少个7组成的
            base += times*12

            remain = target - times*7        #得到剩余部分
            base += map_remain(remain)
            trans_vector.append(base)
        else:  #target < 0
            base = 60   #基数是60
            target = abs(target)
            int_part = math.floor(target)
            times = math.floor(int_part/7)
            base -= times*12
            
            remain = target - times*7
            base -= map2_remain(remain)
            trans_vector.append(base)
    return trans_vector

In [36]:
mid = MidiFile()       #给自己的文件定的.mid后缀
track = MidiTrack()    #定义声部，一个MidoTrack()就是一个声部

In [37]:
def beat(time):            #与mido的拍子互换  
    time /= 60 * 1000  
    time = 1/time  
    return time  

def yin(yin,pai,qian=0,unit = track, liang=64,qi=2): #yin是音，pai是指时间（节拍），
    if type(yin)== str:               #qian是是音前多少拍
        yin = num(yin)                #liang是音量

    unit.append(Message('program_change',channel=0,program=qi,time=0))
    unit.append(Message('note_on',note=yin,velocity=liang,time=qian,channel=0))
    unit.append(Message('note_off',note=yin,velocity=liang,time=int(beat(pai)),channel=0))

In [38]:
midi_sequence = toMidi(final_seq)
midi_jianzou = toMidi(jianzou_seq)
i = 0
for i in range(64):
    midi_target = midi_sequence[i]
    yin(midi_target,120, 0,track,80,2)
    
i = 0                                     #将前一半儿贴上去
for i in range(32):
    midi_target = midi_sequence[i]
    yin(midi_target-12,120, 0,track,80,2)
    
i = 0
for i in range(32):
    midi_target = midi_jianzou[i]
    yin(midi_target-12,120, 0,track,80,2)
    
i = 0
for i in range(64):
    midi_target = midi_sequence[i]
    yin(midi_target,120, 0,track,80,2)

In [39]:
track1 = MidiTrack()
banzou = [6,8,10,10, 6,8,10,10, 2,4,6,6, 1,3,6,6,
          6,8,10,10, 6,8,10,10, 2,4,5.5, 7, 1,3,6,6,
          6,8,10,10, 2,4,6,3, 2,4,6,6, 1,3,6,6,
          6,8,10,10, 6,8,10,10, 2,4,5.5,7, 1,3,6,6,
         
         6,8,10,10, 6,8,10,10, 2,4,6,6, 1,3,6,6,
          6,8,10,10, 6,8,10,10, 2,4,5.5, 7, 1,3,6,6,
          6,8,10,10, 2,4,6,3, 2,4,6,6, 1,3,6,6,
          6,8,10,10, 6,8,10,10, 2,4,5.5,7, 1,3,6,6,
         
         6,8,10,10, 6,8,10,10, 2,4,6,6, 1,3,6,6,
          6,8,10,10, 6,8,10,10, 2,4,5.5, 7, 1,3,6,6,
          6,8,10,10, 2,4,6,3, 2,4,6,6, 1,3,6,6,
          6,8,10,10, 6,8,10,10, 2,4,5.5,7, 1,3,6,6]
banzou_midi = toMidi(banzou)
a=0
for a in range(192):
    yin(banzou_midi[a],120, 0,track1,80,2)


In [40]:
track2 = MidiTrack()
i = 0                                     #将前一半儿贴上去
for i in range(32):
    midi_target = midi_sequence[i]
    yin(midi_target-12,120, 0,track2,80,2)
    
i = 0
for i in range(32):
    midi_target = midi_jianzou[i]
    yin(midi_target-12,120, 0,track2,80,2)

In [41]:
mid.tracks.append(track)
mid.tracks.append(track1)
mid.tracks.append(track2)
mid.save('C:\\Users\\Administrator\\Desktop\\2020Summer\\月repeat_1.mid')