In [1]:
import numpy as np

In [2]:
def FtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-3)
        elif target == 2:
            trans_vector.append(-2)
        elif target == 3:
            trans_vector.append(-1)
        elif target == 4:
            trans_vector.append(1)
        elif target == 5:
            trans_vector.append(2)
        elif target == 6:
            trans_vector.append(3)
        elif target == 7:
            trans_vector.append(4.5)
        elif target == 8:
            trans_vector.append(5)
        elif target == -2:
            trans_vector.append(-5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoF(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -3:
            trans_vector.append(1)
        elif target == -2:
            trans_vector.append(2)
        elif target == -1:
            trans_vector.append(3)
        elif target == 1:
            trans_vector.append(4)
        elif target == 2:
            trans_vector.append(5)
        elif target == 3:
            trans_vector.append(6)
        elif target == 4.5:
            trans_vector.append(7)
        elif target == 5:
            trans_vector.append(8)
        elif target == 0:
            trans_vector.append(0)
        elif target == -4:
            trans_vector.append(-1.5)
        elif target == -5:
            trans_vector.append(-2)
        elif target == -1.5:
            trans_vector.append(2.5)
        elif target == -6:
            trans_vector.append(-3)
        elif target == -7:
            trans_vector.append(-4)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def GtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(-4)
        elif target == 2:
            trans_vector.append(-3)
        elif target == 3:
            trans_vector.append(-2)
        elif target == 5:
            trans_vector.append(1)
        elif target == -2:
            trans_vector.append(-6)
        elif target == -3:
            trans_vector.append(-7)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoG(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -5:
            trans_vector.append(-1)
        elif target == -1:
            trans_vector.append(4.5)
        elif target == -4:
            trans_vector.append(1)
        elif target == -3:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(3)
        elif target == 1:
            trans_vector.append(5)
        elif target == 2:
            trans_vector.append(6)
        elif target == 3:
            trans_vector.append(7)
        elif target == 5:
            trans_vector.append(9)
        elif target == -1.5:
            trans_vector.append(4)
        elif target == -6:
            trans_vector.append(-2)
        elif target == -7:
            trans_vector.append(-3)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [3]:
def count_number(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

In [4]:
FtoC_list = FtoC([6,6, 6,6, 6,6, 5,3, 1,1,2,2,3,3,6,6])
print(FtoC_list)

[3, 3, 3, 3, 3, 3, 2, -1, -3, -3, -2, -2, -1, -1, 3, 3]


In [5]:
GtoC_list = GtoC([2,2,2,2,2,2,1,2])

In [6]:
major_list = FtoC_list + GtoC_list
print(major_list)
count_number(major_list)

[3, 3, 3, 3, 3, 3, 2, -1, -3, -3, -2, -2, -1, -1, 3, 3, -3, -3, -3, -3, -3, -3, -4, -3]


{2: 1, 3: 8, -2: 2, -4: 1, -3: 9, -1: 3}

In [7]:
#映射顺序 2,3,-1,-2,-3,-4
def major_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 2:
            trans_vector.append(0)
        elif target == 3:
            trans_vector.append(1)
        elif target == -1:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(3)
        elif target == -3:
            trans_vector.append(4)
        elif target == -4:
            trans_vector.append(5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [8]:
reflect_major_list = major_reflect(major_list)
print(reflect_major_list)
len(reflect_major_list)

[1, 1, 1, 1, 1, 1, 0, 2, 4, 4, 3, 3, 2, 2, 1, 1, 4, 4, 4, 4, 4, 4, 5, 4]


24

In [9]:
def markoving(darray, vector):
    num = len(vector)
    for i in range(num-1):   #最后一个不用考虑
        row = vector[i]
        column = vector[i+1]
        darray[row][column] += 1
    return darray

In [10]:
F1 = reflect_major_list[0:8]
F2 = reflect_major_list[8:16]
G1 = reflect_major_list[16:24]

major_array = np.zeros((6,6))

major_array = markoving(major_array,F1)
major_array = markoving(major_array,F2)
major_array = markoving(major_array,G1)

print(major_array)

[[0. 0. 1. 0. 0. 0.]
 [1. 6. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 6. 1.]
 [0. 0. 0. 0. 1. 0.]]


In [11]:
def normalize_matrix(matrix):
    mat_size = matrix.shape[0]
    init_array = np.zeros((mat_size,mat_size))
    sum_row_list=[]
    for i in range(mat_size):
        count=0
        for j in range(mat_size):
            count+=matrix[i][j]
        sum_row_list.append(count)
    for k in range(mat_size):
        if sum_row_list[k] == 0:
            init_array[k][k] = 0
        else:
            init_array[k][k] = 1/sum_row_list[k]
    result = np.dot(init_array,matrix)
    
    return result

def sum_rows(matrix):
    sum_row_list1=[]
    for ii in range(len(matrix)):
        count=0
        for jj in range(len(matrix[ii])):
            count+=matrix[ii][jj]
        sum_row_list1.append(count)
    print(sum_row_list1)

In [12]:
markov_major = normalize_matrix(major_array)
print(markov_major)
sum_rows(markov_major)

[[0.         0.         1.         0.         0.         0.        ]
 [0.14285714 0.85714286 0.         0.         0.         0.        ]
 [0.         0.5        0.5        0.         0.         0.        ]
 [0.         0.         0.5        0.5        0.         0.        ]
 [0.         0.         0.         0.125      0.75       0.125     ]
 [0.         0.         0.         0.         1.         0.        ]]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [13]:
#邻接矩阵

def generate_adj(darray, vector):
    num = len(vector)
    for i in range(num-1):
        row = vector[i]
        column = vector[i+1]
        darray[row][column] = 1
    return darray

In [14]:
adj_major = np.zeros((6,6))

adj_major = generate_adj(adj_major,F1)
adj_major = generate_adj(adj_major,F2)
adj_major = generate_adj(adj_major,G1)
print(adj_major)

[[0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0.]]


In [15]:
#邻接矩阵调参数
k=5
x = 0.8

i = 0
Iter_adj_major = 1
for i in range(k):
    Iter_adj_major = np.dot(adj_major,Iter_adj_major)
    
Iter_adj_major = normalize_matrix(Iter_adj_major)

markov_major_final = x*markov_major + (1-x)*Iter_adj_major
sum_rows(markov_major_final)
print(markov_major_final)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[[0.05       0.08333333 0.86666667 0.         0.         0.        ]
 [0.16428571 0.77321429 0.0625     0.         0.         0.        ]
 [0.04761905 0.48571429 0.46666667 0.         0.         0.        ]
 [0.04444444 0.08148148 0.46666667 0.40740741 0.         0.        ]
 [0.01454545 0.04       0.05454545 0.14363636 0.62909091 0.11818182]
 [0.00740741 0.02962963 0.05185185 0.05185185 0.83703704 0.02222222]]


In [16]:
#开始进行迭代
init_array = np.array([1/6,1/6,1/6,1/6,1/6,1/6]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_major_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.05471701]
 [0.2488955 ]
 [0.32814955]
 [0.1004826 ]
 [0.24435466]
 [0.02340067]]
1 	 [[0.06744548]
 [0.37505125]
 [0.27754752]
 [0.07724894]
 [0.17330852]
 [0.02939829]]
2 	 [[0.08437629]
 [0.44452199]
 [0.25844268]
 [0.05788955]
 [0.13363428]
 [0.02113521]]
3 	 [[0.09422742]
 [0.48695994]
 [0.25691549]
 [0.04387527]
 [0.10175906]
 [0.01626281]]
4 	 [[0.10049661]
 [0.51729144]
 [0.25886153]
 [0.03333467]
 [0.07762828]
 [0.01238747]]
5 	 [[0.1050376 ]
 [0.54027292]
 [0.26066259]
 [0.02537335]
 [0.05920401]
 [0.00944953]]
6 	 [[0.10848236]
 [0.55782302]
 [0.26200237]
 [0.01933111]
 [0.04515431]
 [0.00720683]]
7 	 [[0.11111211]
 [0.57121005]
 [0.26300759]
 [0.01473513]
 [0.03443855]
 [0.00549657]]
8 	 [[0.11311796]
 [0.5814147 ]
 [0.26377453]
 [0.01123484]
 [0.02626581]
 [0.00419216]]
9 	 [[0.11464715]
 [0.58919399]
 [0.26436174]
 [0.00856725]
 [0.02003257]
 [0.0031973 ]]
10 	 [[0.115813  ]
 [0.59512552]
 [0.26481082]
 [0.00653355]
 [0.01527857]
 [0.00243854]]
11 	 [[0.11670199]
 

In [17]:
major_list = [2,3,-1,-2,-3,-4]

p_list1 = []

i = 0
for i in range(len(major_list)):
    target_list = res[i]
    p_list1.append(target_list[0])
print(p_list1)

major_12 = np.random.choice(major_list, 12, p=p_list1)

[0.11955843235611258, 0.6141836642070481, 0.2662572779719514, 1.6849888193426786e-07, 3.9407037471530457e-07, 6.289563107796251e-08]


In [18]:
major1 = CtoF(major_12[0:4])

major2 = CtoG(major_12[4:8])

major3 = CtoF(major_12[8:12])

In [19]:
#小调分割线

In [20]:
def EmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(-2.5)
        elif target == 2:
            trans_vector.append(-1.5)
        elif target == 3:
            trans_vector.append(1)
        elif target == 5:
            trans_vector.append(2.5)
        elif target == -3:
            trans_vector.append(-5.5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoEm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -2.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-6)
        elif target == -7:
            trans_vector.append(-5)
        elif target == -1.5:
            trans_vector.append(2)
        elif target == 1:
            trans_vector.append(3)
        elif target == -4:
            trans_vector.append(-2)
        elif target == -3:
            trans_vector.append(-1)
        elif target == -5.5:
            trans_vector.append(-3)
        elif target == 2.5:
            trans_vector.append(5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def AmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-5.5)
        elif target == 2:
            trans_vector.append(-4)
        elif target == 3:
            trans_vector.append(-3)
        elif target == 4:
            trans_vector.append(-2.5)
        elif target == 5:
            trans_vector.append(-1.5)
        elif target == 6:
            trans_vector.append(1)
        elif target == 7:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(-7)
        elif target == -3:
            trans_vector.append(-8.5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoAm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -5.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-3)
        elif target == -7:
            trans_vector.append(-2)
        elif target == -4:
            trans_vector.append(2)
        elif target == -3:
            trans_vector.append(3)
        elif target == -2.5:
            trans_vector.append(4)
        elif target == 2.5:
            trans_vector.append(8)
        elif target == -1.5:
            trans_vector.append(5)
        elif target == 1:
            trans_vector.append(6)
        elif target == 2:
            trans_vector.append(7)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [21]:
EmtoC_list = EmtoC([5,5,5,5,5,5, 5,2,  1,1,1,1,1,1, 1,2])
AmtoC_list = AmtoC([3,3,2,2,1,1,-2,-2])


minor_list = EmtoC_list+AmtoC_list
count_number(minor_list)

{2.5: 7, -7: 2, -5.5: 2, -4: 2, -3: 2, -2.5: 7, -1.5: 2}

In [22]:
#映射顺序 2.5, -1.5,-2.5,-3,-4,-5.5,-7
def minor_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 2.5:
            trans_vector.append(0)
        elif target == -1.5:
            trans_vector.append(1)
        elif target == -2.5:
            trans_vector.append(2)
        elif target == -3:
            trans_vector.append(3)
        elif target == -4:
            trans_vector.append(4)
        elif target == -5.5:
            trans_vector.append(5)
        elif target == -7:
            trans_vector.append(6)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


In [23]:
reflect_minor_list = minor_reflect(minor_list)
print(reflect_minor_list)
len(reflect_minor_list)

[0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 3, 3, 4, 4, 5, 5, 6, 6]


24

In [24]:
minor_array = np.zeros((7,7))

Em1 = reflect_minor_list[0:16]
Am1 = reflect_minor_list[16:24]


minor_array = markoving(minor_array,Em1)
minor_array = markoving(minor_array,Am1)
print(minor_array)

[[6. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 6. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [25]:
markov_minor = normalize_matrix(minor_array)
print(markov_minor)
sum_rows(markov_minor)

[[0.85714286 0.14285714 0.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.14285714 0.85714286 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.5        0.5        0.
  0.        ]
 [0.         0.         0.         0.         0.5        0.5
  0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.5       ]
 [0.         0.         0.         0.         0.         0.
  1.        ]]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [26]:
#第7行为空行，调一下参数

modify_line = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7])
line7 = markov_minor[[6],:] 
lin7 = 0.8*line7 + 0.2*modify_line
markov_minor[[6],:]  = lin7
print(markov_minor)
sum_rows(markov_minor)

[[0.85714286 0.14285714 0.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.14285714 0.85714286 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.5        0.5        0.
  0.        ]
 [0.         0.         0.         0.         0.5        0.5
  0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.5       ]
 [0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
  0.82857143]]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [27]:
#邻接矩阵
adj_minor = np.zeros((7,7))

adj_minor = generate_adj(adj_minor,Em1)
adj_minor = generate_adj(adj_minor,Am1)

print(adj_minor)

[[1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [28]:
k=5
x = 0.8

i = 0
Iter_adj_minor = 1
for i in range(k):
    Iter_adj_minor = np.dot(adj_minor,Iter_adj_minor)

print(Iter_adj_minor)
Iter_adj_minor = normalize_matrix(Iter_adj_minor)


#第五行为空行，调一下参数

modify_line = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7])
Iter_adj_minor[[4],:] = modify_line
print(markov_minor)
sum_rows(Iter_adj_minor)



markov_minor_final = x*markov_minor + (1-x)*Iter_adj_minor
print(markov_minor_final)
sum_rows(markov_minor_final)

[[ 1.  5.  7.  0.  0.  0.  0.]
 [ 0.  3.  5.  0.  0.  0.  0.]
 [ 0.  5.  8.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  5. 10. 10.]
 [ 0.  0.  0.  0.  1.  5. 10.]
 [ 0.  0.  0.  0.  0.  1.  5.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
[[0.85714286 0.14285714 0.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]
 [0.         0.14285714 0.85714286 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.5        0.5        0.
  0.        ]
 [0.         0.         0.         0.         0.5        0.5
  0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.5       ]
 [0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
  0.82857143]]
[1.0, 1.0, 1.0, 1.0, 0.9999999999999998, 0.9999999999999999, 1.0]
[[0.7010989  0.19120879 0.10769231 0.         0.         0.
  0.        ]
 [0.         0.075      0.925      0.         0.         0.
  0.        ]
 [0.         0.19120879 0.80879121 0.  

In [29]:
#开始进行迭代
init_array = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_minor_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.10750392]
 [0.07269231]
 [0.27041601]
 [0.0655887 ]
 [0.12712716]
 [0.13738357]
 [0.21928833]]
1 	 [[0.08401539]
 [0.08635805]
 [0.30617233]
 [0.03538452]
 [0.08825349]
 [0.12407354]
 [0.27574268]]
2 	 [[0.06772732]
 [0.0899084 ]
 [0.34538271]
 [0.02325021]
 [0.05964037]
 [0.1006127 ]
 [0.31347829]]
3 	 [[0.05635278]
 [0.09460263]
 [0.37867071]
 [0.01834816]
 [0.0429197 ]
 [0.07811269]
 [0.33099334]]
4 	 [[0.04830071]
 [0.09906735]
 [0.40863357]
 [0.01627224]
 [0.03400468]
 [0.06121995]
 [0.3325015 ]]
5 	 [[0.04243517]
 [0.1033715 ]
 [0.43590975]
 [0.01520567]
 [0.02930822]
 [0.04995382]
 [0.32381587]]
6 	 [[0.03799013]
 [0.1074555 ]
 [0.46098744]
 [0.01443812]
 [0.02662927]
 [0.0427785 ]
 [0.30972105]]
7 	 [[0.03447502]
 [0.11130824]
 [0.48417034]
 [0.01372648]
 [0.02482244]
 [0.03813986]
 [0.29335763]]
8 	 [[0.03158493]
 [0.1149322 ]
 [0.50568006]
 [0.01301071]
 [0.02336204]
 [0.03492666]
 [0.2765034 ]]
9 	 [[0.02913172]
 [0.11833727]
 [0.52569089]
 [0.01229193]
 [0.02203708]

In [30]:
#映射顺序 2.5, -1.5,-2.5,-3,-4,-5.5,-7
minor_list = [2.5, -1.5,-2.5,-3,-4,-5.5,-7]
p_list2 = []

i = 0
for i in range(len(minor_list)):
    target_list = res[i]
    p_list2.append(target_list[0])
print(p_list2)


minor_12 = np.random.choice(minor_list, 12, p=p_list2)

[0.0022855963419912144, 0.1669094529185086, 0.8036975087675255, 0.001024969069920177, 0.0018431277806909843, 0.0026886796044830064, 0.021550665516881163]


In [31]:
minor1 = CtoEm(minor_12[0:8])
minor2 = CtoAm(minor_12[8:12])

In [32]:
solo_seq = major1+major2+minor1+minor2+major3 + [5,5,5,5,5,5,5,5]
print(solo_seq)
len(solo_seq)

[6, 3, 6, 6, 4.5, 4.5, 7, 7, 1, 1, 1, 1, 1, 1, 2, 2, 5, 4, 4, 4, 6, 6, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5]


32

In [33]:
def find_nearest(num, vector):
    result = num
    mark = 100
    length = len(vector)
    for i in range(length):
        instance = abs(num - vector[i])
        if mark > instance:
            mark = instance
            result = vector[i]
        else:
            continue
    return result

def post_process(vector):
    num = len(vector)
    five_list = [1,2,3,5,6, 8,9,10,12,13, -2,-3,-5,-6,-7,-9]
    C_list = [1,3,5,8,10,12,-7,-5,-3]
    Am_list = [1,3,6,8,10,-2,-5,-7]
    Em_list = [3,5,10,12,-3,-5]
    F_list = [1,6,8,13,-2,-7]
    G_list = [2,5,9,12,-3,-6]
    for i in range(num):
        target = vector[i]
#         int_part = math.floor(target/7)
#         remain_part = target - int_part*7
        if target == 0:
            vector[i] = vector[i-1]
            target = vector[i-1]
        if target in  five_list:
            other = 1
        else:
            if (i>=0 & i<4)|(i>=20 & i<24):
                vector[i] = find_nearest(vector[i],F_list)
            elif (i>=4 & i<8)|(i>=24 & i<32):
                #G chord
                vector[i] = find_nearest(vector[i],G_list)
            elif (i>=8 & i<16):
                #Em chord
                vector[i] = find_nearest(vector[i],Em_list)
            elif (i>=16 & i<20):
                #Am chord
                vector[i] = find_nearest(vector[i],Am_list)
                            
#     #律动感
#     vector[3] = vector[4] = vector[5] = vector[2]
#     vector[11] = vector[12] = vector[13] = vector[10]
#     vector[19] = vector[20] = vector[21] = vector[18]
#     vector[29] = vector[28] = vector[27] = vector[26]
    return vector

In [34]:
postprocessing_solo = post_process(solo_seq)
print(postprocessing_solo)

[6, 3, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 2, 2, 5, 6, 6, 6, 6, 6, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5]


In [35]:
import mido
from mido import Message, MidiFile, MidiTrack

In [36]:
import math

def map_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 4:
        result = 6
    elif num == 4.5:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result   


def map2_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 3.5:
        result = 6
    elif num == 4:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result 
        
        
def toMidi(vector):
    
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target > 0:
            base = 59   #基数是59
            int_part = math.floor(target)     #得到target的整数部分
            times = math.floor(int_part/7)    #整数部分是由多少个7组成的
            base += times*12

            remain = target - times*7        #得到剩余部分
            base += map_remain(remain)
            trans_vector.append(base)
        else:  #target < 0
            base = 60   #基数是60
            target = abs(target)
            int_part = math.floor(target)
            times = math.floor(int_part/7)
            base -= times*12
            
            remain = target - times*7
            base -= map2_remain(remain)
            trans_vector.append(base)
    return trans_vector

In [37]:
mid = MidiFile()       #给自己的文件定的.mid后缀
track = MidiTrack()    #定义声部，一个MidoTrack()就是一个声部

In [38]:
def beat(time):            #与mido的拍子互换  
    time /= 60 * 1000  
    time = 1/time  
    return time  

def yin(yin,pai,qian=0,unit = track, liang=64,qi=2): #yin是音，pai是指时间（节拍），
    if type(yin)== str:               #qian是是音前多少拍
        yin = num(yin)                #liang是音量

    unit.append(Message('program_change',channel=0,program=qi,time=0))
    unit.append(Message('note_on',note=yin,velocity=liang,time=qian,channel=0))
    unit.append(Message('note_off',note=yin,velocity=liang,time=int(beat(pai)),channel=0))

In [39]:
midi_seq = toMidi(postprocessing_solo)
for i in range(len(postprocessing_solo)):
    
    yin(midi_seq[i],80, 0,track,80,2)   
    

In [40]:
track1 = MidiTrack()
track2 = MidiTrack()
track3 = MidiTrack()

def F_chord(track1,track2,track3):
    sq = toMidi([-4,-2,1])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)
    
def C_chord(track1,track2,track3):
    C_sq = toMidi([1,3,5])
    yin(C_sq[0],20, 0,track1,80,2)
    yin(C_sq[1],20, 0,track2,80,2)
    yin(C_sq[2],20, 0,track3,80,2)
    
def G_chord(track1,track2,track3):
    sq = toMidi([-3,-1,2])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)
    
def Em_chord(track1,track2,track3):
    sq = toMidi([-5,-3,-1])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)

def Am_chord(track1,track2,track3):
    sq = toMidi([-2,1,3])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)
    

F_chord(track1,track2,track3)
G_chord(track1,track2,track3)
Em_chord(track1,track2,track3)
Em_chord(track1,track2,track3)

Am_chord(track1,track2,track3)
F_chord(track1,track2,track3)
G_chord(track1,track2,track3)
G_chord(track1,track2,track3)

In [41]:
mid.tracks.append(track)
mid.tracks.append(track1)
mid.tracks.append(track2)
mid.tracks.append(track3)

mid.save('C:\\Users\\Administrator\\Desktop\\final\\solo\\SOLOK=5.mid')