In [1]:
import numpy as np

In [2]:
#大调包含：G C D 每个与C和弦的转换关系
def GtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(-4)
        elif target == 2:
            trans_vector.append(-3)
        elif target == 3:
            trans_vector.append(-2)
        elif target == 5:
            trans_vector.append(1)
        elif target == -2:
            trans_vector.append(-6)
        elif target == -3:
            trans_vector.append(-7)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoG(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -5:
            trans_vector.append(-1)
        elif target == -1:
            trans_vector.append(4.5)
        elif target == -4:
            trans_vector.append(1)
        elif target == -3:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(3)
        elif target == 1:
            trans_vector.append(5)
        elif target == 2:
            trans_vector.append(6)
        elif target == 3:
            trans_vector.append(7)
        elif target == 5:
            trans_vector.append(9)
        elif target == -1.5:
            trans_vector.append(4)
        elif target == -6:
            trans_vector.append(-2)
        elif target == -7:
            trans_vector.append(-3)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def FtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-3)
        elif target == 2:
            trans_vector.append(-2)
        elif target == 3:
            trans_vector.append(-1)
        elif target == 4:
            trans_vector.append(1)
        elif target == 5:
            trans_vector.append(2)
        elif target == 6:
            trans_vector.append(3)
        elif target == 7:
            trans_vector.append(4.5)
        elif target == 8:
            trans_vector.append(5)
        elif target == -2:
            trans_vector.append(-5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoF(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -3:
            trans_vector.append(1)
        elif target == -2:
            trans_vector.append(2)
        elif target == -1:
            trans_vector.append(3)
        elif target == 1:
            trans_vector.append(4)
        elif target == 2:
            trans_vector.append(5)
        elif target == 3:
            trans_vector.append(6)
        elif target == 4.5:
            trans_vector.append(7)
        elif target == 5:
            trans_vector.append(8)
        elif target == 0:
            trans_vector.append(0)
        elif target == -4:
            trans_vector.append(-1.5)
        elif target == -5:
            trans_vector.append(-2)
        elif target == -1.5:
            trans_vector.append(2.5)
        elif target == -6:
            trans_vector.append(-3)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [3]:
def count_number(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

In [4]:
CtoC_list = [1,1,1,-2,1,1,1,-2,1,-2,-3,-3,0,2,1,-2,
                  1,1,1,-2,1,1,1,-2,1,-2,-3,-3,0,-3,-2,3]
print(CtoC_list)

[1, 1, 1, -2, 1, 1, 1, -2, 1, -2, -3, -3, 0, 2, 1, -2, 1, 1, 1, -2, 1, 1, 1, -2, 1, -2, -3, -3, 0, -3, -2, 3]


In [5]:
FtoC_list = FtoC([3,3,3,2,3,3,3,2, 3,5,5,3, 3,3,3,3,  3,2,2,1,2,2,1,-2])
print(FtoC_list)

[-1, -1, -1, -2, -1, -1, -1, -2, -1, 2, 2, -1, -1, -1, -1, -1, -1, -2, -2, -3, -2, -2, -3, -5]


In [6]:
GtoC_list = GtoC([2,2,2,1, 2,2,1,3, 3,2,2,2, 0,2,1,-2,
                  2,1,1,-2, 1,1,1,1])
print(GtoC_list)

[-3, -3, -3, -4, -3, -3, -4, -2, -2, -3, -3, -3, 0, -3, -4, -6, -3, -4, -4, -6, -4, -4, -4, -4]


In [7]:
major_list = CtoC_list + FtoC_list + GtoC_list
print(major_list)
count_number(major_list)

[1, 1, 1, -2, 1, 1, 1, -2, 1, -2, -3, -3, 0, 2, 1, -2, 1, 1, 1, -2, 1, 1, 1, -2, 1, -2, -3, -3, 0, -3, -2, 3, -1, -1, -1, -2, -1, -1, -1, -2, -1, 2, 2, -1, -1, -1, -1, -1, -1, -2, -2, -3, -2, -2, -3, -5, -3, -3, -3, -4, -3, -3, -4, -2, -2, -3, -3, -3, 0, -3, -4, -6, -3, -4, -4, -6, -4, -4, -4, -4]


{0: 3, 1: 15, 2: 3, 3: 1, -1: 13, -6: 2, -5: 1, -4: 9, -3: 17, -2: 16}

In [8]:
#映射顺序 0，1，2，3，-1,-2,-3,-4,-5,-6
def major_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 2:
            trans_vector.append(2)
        elif target == 3:
            trans_vector.append(3)
        elif target == -1:
            trans_vector.append(4)
        elif target == -2:
            trans_vector.append(5)
        elif target == -3:
            trans_vector.append(6)
        elif target == -4:
            trans_vector.append(7)
        elif target == -5:
            trans_vector.append(8)
        elif target == -6:
            trans_vector.append(9)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [9]:
reflect_major_list = major_reflect(major_list)
print(reflect_major_list)

[1, 1, 1, 5, 1, 1, 1, 5, 1, 5, 6, 6, 0, 2, 1, 5, 1, 1, 1, 5, 1, 1, 1, 5, 1, 5, 6, 6, 0, 6, 5, 3, 4, 4, 4, 5, 4, 4, 4, 5, 4, 2, 2, 4, 4, 4, 4, 4, 4, 5, 5, 6, 5, 5, 6, 8, 6, 6, 6, 7, 6, 6, 7, 5, 5, 6, 6, 6, 0, 6, 7, 9, 6, 7, 7, 9, 7, 7, 7, 7]


In [10]:
def markoving(darray, vector):
    num = len(vector)
    for i in range(num-1):   #最后一个不用考虑
        row = vector[i]
        column = vector[i+1]
        darray[row][column] += 1
    return darray

In [11]:
major_array = np.zeros((10,10))
#先处理C1和旋部分：
C1 = reflect_major_list[0:16]
print(C1)
major_array = markoving(major_array,C1)
print(major_array)

[1, 1, 1, 5, 1, 1, 1, 5, 1, 5, 6, 6, 0, 2, 1, 5]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
#处理C2和旋部分
C2 = reflect_major_list[16:32]
print(C2)
major_array = markoving(major_array,C2)
print(major_array)

[1, 1, 1, 5, 1, 1, 1, 5, 1, 5, 6, 6, 0, 6, 5, 3]
[[0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 8. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 1. 0. 0. 2. 0. 0. 0.]
 [2. 0. 0. 0. 0. 1. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#处理F1和旋部分
F1 = reflect_major_list[32:48]
print(F1)
major_array = markoving(major_array,F1)
print(major_array)

[4, 4, 4, 5, 4, 4, 4, 5, 4, 2, 2, 4, 4, 4, 4, 4]
[[0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 8. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 8. 2. 0. 0. 0. 0.]
 [0. 4. 0. 1. 2. 0. 2. 0. 0. 0.]
 [2. 0. 0. 0. 0. 1. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
#处理F2和旋部分
F2 = reflect_major_list[48:56]
print(F2)
major_array = markoving(major_array,F2)
print(major_array)

[4, 5, 5, 6, 5, 5, 6, 8]
[[0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 8. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 8. 3. 0. 0. 0. 0.]
 [0. 4. 0. 1. 2. 2. 4. 0. 0. 0.]
 [2. 0. 0. 0. 0. 2. 2. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
#处理G1和旋部分
G1 = reflect_major_list[56:72]
print(G1)
major_array = markoving(major_array,G1)
print(major_array)

[6, 6, 6, 7, 6, 6, 7, 5, 5, 6, 6, 6, 0, 6, 7, 9]
[[0. 0. 1. 0. 0. 0. 2. 0. 0. 0.]
 [0. 8. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 8. 3. 0. 0. 0. 0.]
 [0. 4. 0. 1. 2. 3. 5. 0. 0. 0.]
 [3. 0. 0. 0. 0. 2. 7. 3. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
#处理G2和旋部分
G2 = reflect_major_list[72:80]
print(G2)
major_array = markoving(major_array,G2)
print(major_array)

[6, 7, 7, 9, 7, 7, 7, 7]
[[0. 0. 1. 0. 0. 0. 2. 0. 0. 0.]
 [0. 8. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 8. 3. 0. 0. 0. 0.]
 [0. 4. 0. 1. 2. 3. 5. 0. 0. 0.]
 [3. 0. 0. 0. 0. 2. 7. 4. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 4. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [17]:
def normalize_matrix(matrix):
    mat_size = matrix.shape[0]
    init_array = np.zeros((mat_size,mat_size))
    sum_row_list=[]
    for i in range(mat_size):
        count=0
        for j in range(mat_size):
            count+=matrix[i][j]
        sum_row_list.append(count)
    for k in range(mat_size):
        if sum_row_list[k] == 0:
            init_array[k][k] = 0
        else:
            init_array[k][k] = 1/sum_row_list[k]
    result = np.dot(init_array,matrix)
    
    return result

def sum_rows(matrix):
    sum_row_list1=[]
    for ii in range(len(matrix)):
        count=0
        for jj in range(len(matrix[ii])):
            count+=matrix[ii][jj]
        sum_row_list1.append(count)
    print(sum_row_list1)

In [18]:
markov_major = normalize_matrix(major_array)
print(markov_major)

[[0.         0.         0.33333333 0.         0.         0.
  0.66666667 0.         0.         0.        ]
 [0.         0.53333333 0.         0.         0.         0.46666667
  0.         0.         0.         0.        ]
 [0.         0.33333333 0.33333333 0.         0.33333333 0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.08333333 0.         0.66666667 0.25
  0.         0.         0.         0.        ]
 [0.         0.26666667 0.         0.06666667 0.13333333 0.2
  0.33333333 0.         0.         0.        ]
 [0.17647059 0.         0.         0.         0.         0.11764706
  0.41176471 0.23529412 0.05882353 0.        ]
 [0.         0.         0.         0.         0.         0.125
  0.125      0.5        0.         0.25      ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.

In [19]:
#第四行为空行，调一下参数

modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line4 = markov_major[3]
line4 = modify_line
markov_major[[3],:] = line4
print(markov_major)
sum_rows(markov_major)

#第9行为空行，调一下参数

modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line9 = markov_major[8]
line9 = modify_line
markov_major[[8],:] = line9
print(markov_major)
sum_rows(markov_major)

[[0.         0.         0.33333333 0.         0.         0.
  0.66666667 0.         0.         0.        ]
 [0.         0.53333333 0.         0.         0.         0.46666667
  0.         0.         0.         0.        ]
 [0.         0.33333333 0.33333333 0.         0.33333333 0.
  0.         0.         0.         0.        ]
 [0.1        0.1        0.1        0.1        0.1        0.1
  0.1        0.1        0.1        0.1       ]
 [0.         0.         0.08333333 0.         0.66666667 0.25
  0.         0.         0.         0.        ]
 [0.         0.26666667 0.         0.06666667 0.13333333 0.2
  0.33333333 0.         0.         0.        ]
 [0.17647059 0.         0.         0.         0.         0.11764706
  0.41176471 0.23529412 0.05882353 0.        ]
 [0.         0.         0.         0.         0.         0.125
  0.125      0.5        0.         0.25      ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0

In [20]:
#邻接矩阵

def generate_adj(darray, vector):
    num = len(vector)
    for i in range(num-1):
        row = vector[i]
        column = vector[i+1]
        darray[row][column] = 1
    return darray

In [21]:
adj_major = np.zeros((10,10))
#先处理C1和旋部分：
C1 = reflect_major_list[0:16]
# print(C1)
adj_major = generate_adj(adj_major,C1)
# print(adj_major)

#处理C2和旋部分
C2 = reflect_major_list[16:32]
adj_major = generate_adj(adj_major,C2)
# print(adj_major)

#处理F1和旋部分
F1 = reflect_major_list[32:48]
adj_major = generate_adj(adj_major,F1)
# print(adj_major)

#处理F2和旋部分
F2 = reflect_major_list[48:56]
adj_major = generate_adj(adj_major,F2)
# print(adj_major)

#处理G1和旋部分
G1 = reflect_major_list[56:72]
adj_major = generate_adj(adj_major,G1)
# print(adj_major)

#处理G2和旋部分
G2 = reflect_major_list[72:80]
adj_major = generate_adj(adj_major,G2)
print(adj_major)

[[0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [22]:
#邻接矩阵调参数
k=4
x = 0.8

i = 0
Iter_adj_major = 1
for i in range(k):
    Iter_adj_major = np.dot(adj_major,Iter_adj_major)
    
Iter_adj_major = normalize_matrix(Iter_adj_major)

#第4行为空行，调一下参数
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line4 = Iter_adj_major[3]
line4 = modify_line
Iter_adj_major[[3],:] = line4
# print(Iter_adj_major)

#第9行为空行，调一下参数
modify_line = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])
line9 = Iter_adj_major[8]
line9 = modify_line
Iter_adj_major[[8],:] = line9
# print(Iter_adj_major)

markov_major_final = x*markov_major + (1-x)*Iter_adj_major
sum_rows(markov_major_final)
print(markov_major_final)

[1.0, 0.9999999999999999, 1.0, 0.9999999999999999, 0.9999999999999998, 1.0, 0.9999999999999998, 0.9999999999999999, 0.9999999999999999, 1.0]
[[0.01       0.0275     0.28416667 0.0125     0.0275     0.0425
  0.56333333 0.0175     0.01       0.005     ]
 [0.0084507  0.45765258 0.01408451 0.01690141 0.02816901 0.42122066
  0.03098592 0.01126761 0.0084507  0.0028169 ]
 [0.00487805 0.30569106 0.29105691 0.01463415 0.30569106 0.04878049
  0.0195122  0.00487805 0.00487805 0.        ]
 [0.1        0.1        0.1        0.1        0.1        0.1
  0.1        0.1        0.1        0.1       ]
 [0.00550459 0.03486239 0.09051988 0.0146789  0.57003058 0.24587156
  0.02385321 0.00733945 0.00550459 0.00183486]
 [0.01006289 0.24100629 0.0163522  0.06716981 0.13433962 0.20528302
  0.29685535 0.01509434 0.01006289 0.00377358]
 [0.15247591 0.02146893 0.01355932 0.01242938 0.02146893 0.1370555
  0.36556996 0.20970422 0.05835826 0.0079096 ]
 [0.01190476 0.0202381  0.01071429 0.01309524 0.0202381  0.1428571

In [23]:
#开始进行迭代
init_array = np.array([1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_major_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.04152769]
 [0.13244193]
 [0.09284538]
 [0.03634089]
 [0.13234373]
 [0.14875684]
 [0.16770147]
 [0.17175932]
 [0.03211593]
 [0.04416683]]
1 	 [[0.0392037 ]
 [0.14523036]
 [0.06641491]
 [0.02776023]
 [0.14330748]
 [0.18146854]
 [0.17005911]
 [0.15726542]
 [0.02342003]
 [0.04587022]]
2 	 [[0.03802885]
 [0.14926238]
 [0.05793185]
 [0.028051  ]
 [0.14422529]
 [0.19147792]
 [0.17582072]
 [0.15184865]
 [0.02202329]
 [0.04133005]]
3 	 [[0.03876451]
 [0.1507573 ]
 [0.05530565]
 [0.02850172]
 [0.14341203]
 [0.19469844]
 [0.17918402]
 [0.14703266]
 [0.02221668]
 [0.04012699]]
4 	 [[0.03930509]
 [0.15142659]
 [0.05479922]
 [0.02873084]
 [0.14266053]
 [0.19547689]
 [0.18111662]
 [0.14482472]
 [0.02244071]
 [0.03921879]]
5 	 [[0.03962018]
 [0.15178195]
 [0.05480017]
 [0.02881228]
 [0.14224323]
 [0.19568692]
 [0.18205838]
 [0.14360834]
 [0.02257391]
 [0.03881465]]
6 	 [[0.03977188]
 [0.1520002 ]
 [0.05487861]
 [0.02884261]
 [0.14206313]
 [0.19574954]
 [0.18248235]
 [0.14298678]
 [0.02263698]


In [24]:
major_list = [0,1,2,3,-1,-2,-3,-4,-5,-6]
p_list1 = []

i = 0
for i in range(len(major_list)):
    target_list = res[i]
    p_list1.append(target_list[0])
print(p_list1)

# i = 0
# count = 0
# for i in range(len(p_list)):
#     count += p_list[i]
# print(count)
# 主歌大调：K=3，x=0.8
major_80 = np.random.choice(major_list, 80, p=p_list1)


[0.03988159073295312, 0.15239986530772223, 0.055021828647884616, 0.028871718085446803, 0.1420926070032163, 0.19591372960751238, 0.18276099915345284, 0.14208670821437844, 0.02268055551825509, 0.038290397729177764]


In [25]:
print("C1\n")
major1 = major_80[0:8]
major1 = major1.tolist()
print(major_80[0:8])

print("F1\n")
print(CtoF(major_80[8:16]))
major2 = CtoF(major_80[8:16])
# major2 = major2.to_list()

print("G1\n")
print(CtoG(major_80[16:24]))
major3 = CtoG(major_80[16:24]) 
# major3 = major3.to_list()

print("C2\n")
print(major_80[24:32])
major4 = major_80[24:32]
major4 = major4.tolist()

print("F2\n")
print(CtoF(major_80[32:36]))
major5 = CtoF(major_80[32:36])
# major5 = major5.to_list()

print("G2\n")
print(CtoG(major_80[36:40]))
major6 = CtoG(major_80[36:40])
# major6 = major6.to_list()

C1

[-1  1 -2  2 -3  1  1  2]
F1

[4, 1, 4, -1.5, 1, 3, 1, 1]
G1

[4.5, 2, 3, 1, 2, 1, 1, 4.5]
C2

[-2 -2  0 -4 -3 -1 -3  1]
F2

[3, 2, 0, 4]
G2

[3, 7, 4.5, 4.5]


In [26]:
#小调部分
def EmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 3:
            trans_vector.append(1)
        elif target == 5:
            trans_vector.append(2.5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoEm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -2.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-6)
        elif target == -7:
            trans_vector.append(-5)
        elif target == -1.5:
            trans_vector.append(2)
        elif target == 1:
            trans_vector.append(3)
        elif target == -4:
            trans_vector.append(-2)
        elif target == -3:
            trans_vector.append(-1)
        elif target == -5.5:
            trans_vector.append(-3)
        elif target == 2.5:
            trans_vector.append(5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def AmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-5.5)
        elif target == 2:
            trans_vector.append(-4)
        elif target == 3:
            trans_vector.append(-3)
        elif target == 4:
            trans_vector.append(-2.5)
        elif target == 5:
            trans_vector.append(-1.5)
        elif target == 6:
            trans_vector.append(1)
        elif target == 7:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(-7)
        elif target == -3:
            trans_vector.append(-8.5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoAm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -5.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-3)
        elif target == -7:
            trans_vector.append(-2)
        elif target == -4:
            trans_vector.append(2)
        elif target == -3:
            trans_vector.append(3)
        elif target == -2.5:
            trans_vector.append(4)
        elif target == 2.5:
            trans_vector.append(8)
        elif target == -1.5:
            trans_vector.append(5)
        elif target == 1:
            trans_vector.append(6)
        elif target == 2:
            trans_vector.append(7)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [27]:
AmtoC_list = AmtoC([1,1,1,-2,1,1,1,3,2,1,1,1,0,-3,-2,3])
EmtoC_list = EmtoC([5,5,5,3,5,5,5,3])
AmtoC_list2 = AmtoC([2,1,1,1,0,2,1,2])
minor_list = AmtoC_list+EmtoC_list+AmtoC_list2
count_number(minor_list)

{0: 2, 1: 2, 2.5: 6, -8.5: 1, -7: 2, -5.5: 13, -4: 4, -3: 2}

In [28]:
#映射顺序 0，1，2.5, -3,-4,-5.5,-7,-8.5
def minor_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 2.5:
            trans_vector.append(2)
        elif target == -3:
            trans_vector.append(3)
        elif target == -4:
            trans_vector.append(4)
        elif target == -5.5:
            trans_vector.append(5)
        elif target == -7:
            trans_vector.append(6)
        elif target == -8.5:
            trans_vector.append(7)
        else:
            print(target)
            print("没有被添加")
    return trans_vector



In [29]:
reflect_minor_list = minor_reflect(minor_list)
print(reflect_minor_list)

[5, 5, 5, 6, 5, 5, 5, 3, 4, 5, 5, 5, 0, 7, 6, 3, 2, 2, 2, 1, 2, 2, 2, 1, 4, 5, 5, 5, 0, 4, 5, 4]


In [30]:
minor_array = np.zeros((8,8))
#先处理Am1和旋部分：
Am1 = reflect_minor_list[0:16]
# print(Em1)
minor_array = markoving(minor_array,Am1)
# print(minor_array)

#先处理Em1和旋部分：
Em1 = reflect_minor_list[16:24]
# print(Bm1)
minor_array = markoving(minor_array,Em1)
# print(minor_array)

#先处理Am2和旋部分：
Am2 = reflect_minor_list[24:]
# print(Em2)
minor_array = markoving(minor_array,Am2)
print(minor_array)

[[0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 2. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0.]
 [2. 0. 0. 1. 1. 8. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In [31]:
markov_minor = normalize_matrix(minor_array)
print(markov_minor)
sum_rows(markov_minor)

[[0.         0.         0.         0.         0.5        0.
  0.         0.5       ]
 [0.         0.         1.         0.         0.         0.
  0.         0.        ]
 [0.         0.33333333 0.66666667 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.        ]
 [0.15384615 0.         0.         0.07692308 0.07692308 0.61538462
  0.07692308 0.        ]
 [0.         0.         0.         0.5        0.         0.5
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [32]:
#邻接矩阵
adj_minor = np.zeros((8,8))

#先处理Em1和旋部分：
Am1 = reflect_minor_list[0:16]
adj_minor = generate_adj(adj_minor,Am1)

#先处理Bm1和旋部分：
Em1 = reflect_minor_list[16:24]
adj_minor = generate_adj(adj_minor,Em1)

#先处理Em2和旋部分：
Am2 = reflect_minor_list[24:]
adj_minor = generate_adj(adj_minor,Am2)
print(adj_minor)

[[0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In [33]:
k = 4
x = 0.8

i = 0
Iter_adj_minor = 1
for i in range(k):
    Iter_adj_minor = np.dot(adj_minor,Iter_adj_minor)

# print(Iter_adj_minor)
Iter_adj_minor = normalize_matrix(Iter_adj_minor)
# print(Iter_adj_minor)

markov_minor_final = x*markov_minor + (1-x)*Iter_adj_minor
print(markov_minor_final)
sum_rows(markov_minor_final)

[[0.02352941 0.         0.         0.03529412 0.45882353 0.04705882
  0.02352941 0.41176471]
 [0.         0.08       0.92       0.         0.         0.
  0.         0.        ]
 [0.         0.34166667 0.65833333 0.         0.         0.
  0.         0.        ]
 [0.01818182 0.         0.         0.03636364 0.85454545 0.05454545
  0.01818182 0.01818182]
 [0.024      0.         0.         0.032      0.048      0.856
  0.032      0.008     ]
 [0.14641026 0.         0.         0.09820513 0.10820513 0.54897436
  0.08820513 0.01      ]
 [0.02666667 0.         0.         0.43333333 0.04666667 0.45333333
  0.03333333 0.00666667]
 [0.01666667 0.         0.         0.03333333 0.05       0.06666667
  0.81666667 0.01666667]]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [34]:
#开始进行迭代
init_array = np.array([1/8,1/8,1/8,1/8,1/8,1/8,1/8, 1/8]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_minor_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.03193185]
 [0.05270833]
 [0.19729167]
 [0.08356619]
 [0.1957801 ]
 [0.25332233]
 [0.12648954]
 [0.05890998]]
1 	 [[0.04841332]
 [0.07162465]
 [0.17837535]
 [0.09208409]
 [0.13171876]
 [0.37398532]
 [0.08320615]
 [0.02059236]]
2 	 [[0.06329197]
 [0.06667488]
 [0.18332512]
 [0.08274191]
 [0.15260542]
 [0.3644536 ]
 [0.05960645]
 [0.02730067]]
3 	 [[0.06206041]
 [0.06797007]
 [0.18202993]
 [0.0726567 ]
 [0.15065404]
 [0.36703919]
 [0.0643061 ]
 [0.03328356]]
4 	 [[0.06240483]
 [0.06763116]
 [0.18236884]
 [0.07467392]
 [0.14217527]
 [0.36870955]
 [0.06930206]
 [0.03273438]]
5 	 [[0.06261475]
 [0.06771985]
 [0.18228015]
 [0.07679875]
 [0.14403655]
 [0.36472317]
 [0.06894088]
 [0.0328859 ]]
6 	 [[0.06211224]
 [0.06769664]
 [0.18230336]
 [0.07640005]
 [0.14559735]
 [0.36410015]
 [0.0688041 ]
 [0.03298611]]
7 	 [[0.06203743]
 [0.06770271]
 [0.18229729]
 [0.07630064]
 [0.14503221]
 [0.36499345]
 [0.0688573 ]
 [0.03277896]]
8 	 [[0.06214906]
 [0.06770112]
 [0.18229888]
 [0.07638018]
 [0.

In [35]:
#映射顺序 0，1，-1.5,-2.5,-4,-5.5
minor_list = [0,1,2.5, -3,-4,-5.5,-7,-8.5]
p_list2 = []

i = 0
for i in range(len(minor_list)):
    target_list = res[i]
    p_list2.append(target_list[0])
print(p_list2)

#主歌大调：K=3，x=0.8
minor_32 = np.random.choice(minor_list, 32, p=p_list2)


[0.06214188072162751, 0.06770145310435932, 0.1822985468956407, 0.07633465378803796, 0.14504187601556373, 0.3649398286660685, 0.06875144323162537, 0.03279031757707735]


In [36]:
print("Am1\n")
print(CtoAm(minor_32[0:8]))
minor1 = CtoAm(minor_32[0:8])

print("Em\n")
print(CtoEm(minor_32[8:12]))
minor2 = CtoEm(minor_32[8:12])

print("Am2\n")
print(CtoAm(minor_32[12:16]))
minor3 = CtoAm(minor_32[12:16])

Am1

[3, -2, 1, 6, 2, 1, 1, 8]
Em

[-3, -3, -2, 0]
Am2

[2, 2, 1, 8]


In [37]:
zhuge_seq = major1 + minor1 + major2 + major3 + major4 + minor2 + minor3 + major5 + major6 + [1,1,1,1,1,1,1,1]
print(zhuge_seq)

[-1, 1, -2, 2, -3, 1, 1, 2, 3, -2, 1, 6, 2, 1, 1, 8, 4, 1, 4, -1.5, 1, 3, 1, 1, 4.5, 2, 3, 1, 2, 1, 1, 4.5, -2, -2, 0, -4, -3, -1, -3, 1, -3, -3, -2, 0, 2, 2, 1, 8, 3, 2, 0, 4, 3, 7, 4.5, 4.5, 1, 1, 1, 1, 1, 1, 1, 1]


In [38]:
def find_nearest(num, vector):
    result = num
    mark = 100
    length = len(vector)
    for i in range(length):
        instance = abs(num - vector[i])
        if mark > instance:
            mark = instance
            result = vector[i]
        else:
            continue
    return result

def post_process(vector):
    num = len(vector)
    five_list = [1,2,3,5,6, 8,9,10,12,13, -2,-3,-5,-6,-7,-9]
    C_list = [1,3,5,8,10,12,-7,-5,-3]
    Am_list = [1,3,6,8,10,-2,-5,-7]
    Em_list = [3,5,10,12,-3,-5]
    F_list = [1,6,8,13,-2,-7]
    G_list = [2,5,9,12,-3,-6]
    for i in range(num):
        target = vector[i]
#         int_part = math.floor(target/7)
#         remain_part = target - int_part*7
        if target == 0:
            vector[i] = vector[i-1]
            target = vector[i-1]
        if target in  five_list:
            continue
        else:
            if i>=0 & i<8:
                vector[i] = find_nearest(vector[i],C_list)
            elif i>=8 & i<16:
                #Am chord
                vector[i] = find_nearest(vector[i],Am_list)
            elif i>=16 & i<24:
                #F chord
                vector[i] = find_nearest(vector[i],F_list)
            elif i>=24 & i<32:
                #G chord
                vector[i] = find_nearest(vector[i],G_list)
            elif i>=32 & i<40:
                #C chord
                vector[i] = find_nearest(vector[i],C_list)
            elif i>=40 & i<44:
                #Em chord
                vector[i] = find_nearest(vector[i],Em_list)
            elif i>=44 & i<48:
                #Am chord
                vector[i] = find_nearest(vector[i],Am_list)
            elif i>=48 & i<52:
                #F chord
                vector[i] = find_nearest(vector[i],F_list)
            elif i>=52 & i<56:
                #G chord
                vector[i] = find_nearest(vector[i],G_list)
                
    #律动感
    vector[6] = vector[5]
    vector[14] = vector[13]
    vector[23] = vector[22]
    vector[30] = vector[29]
    vector[38] = vector[37]
    vector[46] = vector[45]
    vector[55] = vector[54]
    return vector

In [39]:
postprocessing_zhuge = post_process(zhuge_seq)
print(postprocessing_zhuge)

[1, 1, -2, 2, -3, 1, 1, 2, 3, -2, 1, 6, 2, 1, 1, 8, 3, 1, 3, -3, 1, 3, 1, 1, 5, 2, 3, 1, 2, 1, 1, 5, -2, -2, -2, -5, -3, 1, 1, 1, -3, -3, -2, -2, 2, 2, 2, 8, 3, 2, 2, 3, 3, 8, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1]


In [40]:
import mido
from mido import Message, MidiFile, MidiTrack

In [41]:
import math

def map_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 4:
        result = 6
    elif num == 4.5:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result   


def map2_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 3.5:
        result = 6
    elif num == 4:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result 
        
        
def toMidi(vector):
    
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target > 0:
            base = 59   #基数是59
            int_part = math.floor(target)     #得到target的整数部分
            times = math.floor(int_part/7)    #整数部分是由多少个7组成的
            base += times*12

            remain = target - times*7        #得到剩余部分
            base += map_remain(remain)
            trans_vector.append(base)
        else:  #target < 0
            base = 60   #基数是60
            target = abs(target)
            int_part = math.floor(target)
            times = math.floor(int_part/7)
            base -= times*12
            
            remain = target - times*7
            base -= map2_remain(remain)
            trans_vector.append(base)
    return trans_vector

In [42]:
mid = MidiFile()       #给自己的文件定的.mid后缀
track = MidiTrack()    #定义声部，一个MidoTrack()就是一个声部

In [43]:
def beat(time):            #与mido的拍子互换  
    time /= 60 * 1000  
    time = 1/time  
    return time  

def yin(yin,pai,qian=0,unit = track, liang=64,qi=2): #yin是音，pai是指时间（节拍），
    if type(yin)== str:               #qian是是音前多少拍
        yin = num(yin)                #liang是音量

    unit.append(Message('program_change',channel=0,program=qi,time=0))
    unit.append(Message('note_on',note=yin,velocity=liang,time=qian,channel=0))
    unit.append(Message('note_off',note=yin,velocity=liang,time=int(beat(pai)),channel=0))

In [44]:
zhuge_k49 = [1, 2, 1, -5, -2, -3, -3, -5, 2, 1, 6, 8, 6, 8, 8, 2, 2, 3, 2, 3, 2, -3, -3, -3, 5, 5, 2, 3, 5, -2, -2, 2, -3, -2, 1, 1, -2, 1, 1, -6, 5, -2, 5, 1, -2, 8, 8, 8, -3, 1, 3, -3, 3, 8, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]
zhuge_k41 = [2, 1, -6, -3, 1, 1, 1, -2, 2, 2, 1, 1, 1, 8, 8, 1, 1, -3, 1, 5, 2, 3, 3, 3, 5, 3, 5, 2, 5, 6, 6, 5, -2, 2, -5, 1, 1, -3, -3, -3, -6, 5, -3, -2, -2, 2, 2, 3, 3, 3, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
zhuge_k42 = [-5, -2, -2, 1, -3, 1, 1, 1, 1, 1, 1, 3, 3, 6, 6, 6, 5, 3, 1, 2, 3, 3, 2, 2, 3, 5, 1, 5, 1, 1, 1, 1, -3, -3, 1, 1, -2, -5, -5, -3, -3, -6, -3, -2, 2, -2, -2, 6, 2, 3, 2, 2, 2, 2, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1]
zhuge_kk4 = [3, -5, 1, 1, -3, -2, -2, -5, 1, 3, 2, 8, 1, 1, 1, 2, -3, 5, 5, 2, 3, 3, -3, -3, 5, 5, 5, 2, 1, 5, 5, 6, -2, -3, 1, -3, 1, 1, 1, 1, -2, 3, -3, 5, 8, 2, 2, 6, -3, 1, 2, 1, 5, 2, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1]
zhuge_kk5 = [-2, 1, 1, -2, -5, -5, -5, -5, 8, 2, 6, 8, 1, 1, 1, 2, 6, 1, 2, 3, 1, -3, 1, 1, 3, 1, 3, 5, 6, 8, 8, -2, 3, 1, 1, -2, -2, -2, -2, -3, -5, 1, -2, -2, 1, 8, 8, 2, 1, 2, 2, 3, 2, 2, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1]
zhuge_1 = [1, -5, 1, 1, -2, 1, 1, 1, 1, -2, 2, 1, 8, 1, 1, 1, -3, 2, 5, -3, 1, 1, 3, 3, 5, 3, 8, 5, 5, 5, 5, 5, -2, -3, -2, 1, -5, 2, 2, -2, -3, 5, 5, 5, 6, 1, 1, 1, 1, 5, 1, 3, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1]

In [45]:
zhuge_sequence = zhuge_1
midi_sequence = toMidi(zhuge_sequence)
five_list = [1,2,3,5,6, 8,9,10,12,13, -2,-3,-5,-6,-7,-9]
C_list = [1,3,5,8,10,12,-7,-5,-3]
Am_list = [1,3,6,8,10,-2,-5,-7]
Em_list = [3,5,10,12,-3,-5]
F_list = [1,6,8,13,-2,-7]
G_list = [2,5,9,12,-3,-6]
i=0
for i in range(64):    #16个小节，每小节8拍，一共128
    target = zhuge_sequence[i]
    midi_target = midi_sequence[i]
    if (target>= 6)&(target<=7):    #框定在一个区间
        target -= 8
        midi_target = midi_sequence[i]-12
    elif (target > 7):
        target -= 7
        midi_target = midi_sequence[i]-12
    elif (target < -3) & (target>=-7):
        target += 8
        midi_target = midi_sequence[i]+12
    elif (target<-7):
        target +=7
        midi_target = midi_sequence[i]+12
#     else:
#         continue
    
    if i == 63:
        next_target = target
    else:
        next_target = zhuge_sequence[i+1]
        if (next_target>= 6)&(next_target<=7):    #框定在一个区间
            next_target -= 8
        elif (next_target > 7):
            next_target -= 7
        elif (next_target < -3) & (next_target>=-7):
            next_target += 8
        elif (next_target<-7):
            next_target +=7
#         else:
#             continue
        
    distance = abs(target-next_target)
    if target > next_target:
        big = target
        small = next_target
    else:
        big = next_target
        small = target
        
    if distance >=5:
        if (i <= 7) | (i>31 & i<=39):
            #CCCCCC
#             new_Arr = np.random.choice(major_list, 1, p=p_list1)
#             new_list = new_Arr.tolist()
#             new = new_list[0]
            while(True):
                new_Arr = np.random.choice(major_list, 1, p=p_list1)
                new_list = new_Arr.tolist()
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue   
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, C_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)                 
                
        elif (i>7 & i <= 15) | (i>43 & i<= 47):
            #amamamamamam
            while(True):
                new_Arr = np.random.choice(minor_list, 1, p=p_list2)
                new_list = new_Arr.tolist()
                new_list = CtoAm(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue   
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, Am_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)    
        elif (i>15 & i <= 23) | (i>47 & i<=52):
            #FFFFFF
#             new_Arr = np.random.choice(major_list, 1, p=p_list1)
#             new_list = new_Arr.tolist()
#             new_list = CtoF(new_list)
#             new = new_list[0]
            while(True):
                new_Arr = np.random.choice(major_list, 1, p=p_list1)
                new_list = new_Arr.tolist()
                new_list = CtoF(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue        
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, F_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)    
        elif (i>23 & i<=31) | (i>52 & i<=56):
            #GGGGG
            while(True):
                new_Arr = np.random.choice(major_list, 1, p=p_list1)
                new_list = new_Arr.tolist()
                new_list = CtoG(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue            
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, G_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
        elif (i>39 & i<=43):
            #EMEMEMEMEM
            while(True):
                new_Arr = np.random.choice(minor_list, 1, p=p_list2)
                new_list = new_Arr.tolist()
                new_list = CtoEm(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue     
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, Em_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
    else:
        yin(midi_target,80, 0,track,80,2)   

In [46]:
track1 = MidiTrack()
track2 = MidiTrack()
track3 = MidiTrack()
rhythm1 = [1,1, -2,-2,-4,-4,-3,-3,
          1,1,-5,-2,-4,-3,1,1,]
rhythm2 = [3,3,1,1,-2,-2,-1,-1,
          3,3,-3,1,-2,-1,3,3]
rhythm3 = [5,5,3,3,1,1,2,2,
          5,5,-1,3,1,2,5,5]

rhythm1 = toMidi(rhythm1)
rhythm2 = toMidi(rhythm2)
rhythm3 = toMidi(rhythm3)

a=0
for a in range(16):
    yin(rhythm1[a],20, 0,track1,80,2)

b=0
for b in range(16):
    yin(rhythm2[b],20, 0,track2,80,2)

c=0
for c in range(16):
    yin(rhythm3[c],20, 0,track3,80,2)

In [47]:
mid.tracks.append(track)
mid.tracks.append(track1)
mid.tracks.append(track2)
mid.tracks.append(track3)

mid.save('C:\\Users\\Administrator\\Desktop\\2020Summer\\青花瓷压缩3.mid')

In [48]:
print("hello")

hello
