In [1]:
import numpy as np

In [2]:
def FtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-3)
        elif target == 2:
            trans_vector.append(-2)
        elif target == 3:
            trans_vector.append(-1)
        elif target == 4:
            trans_vector.append(1)
        elif target == 5:
            trans_vector.append(2)
        elif target == 6:
            trans_vector.append(3)
        elif target == 7:
            trans_vector.append(4.5)
        elif target == 8:
            trans_vector.append(5)
        elif target == -2:
            trans_vector.append(-5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoF(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -3:
            trans_vector.append(1)
        elif target == -2:
            trans_vector.append(2)
        elif target == -1:
            trans_vector.append(3)
        elif target == 1:
            trans_vector.append(4)
        elif target == 2:
            trans_vector.append(5)
        elif target == 3:
            trans_vector.append(6)
        elif target == 4.5:
            trans_vector.append(7)
        elif target == 5:
            trans_vector.append(8)
        elif target == 0:
            trans_vector.append(0)
        elif target == -4:
            trans_vector.append(-1.5)
        elif target == -5:
            trans_vector.append(-2)
        elif target == -1.5:
            trans_vector.append(2.5)
        elif target == -6:
            trans_vector.append(-3)
        elif target == -7:
            trans_vector.append(-4)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def GtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(-4)
        elif target == 2:
            trans_vector.append(-3)
        elif target == 3:
            trans_vector.append(-2)
        elif target == 5:
            trans_vector.append(1)
        elif target == -2:
            trans_vector.append(-6)
        elif target == -3:
            trans_vector.append(-7)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoG(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -5:
            trans_vector.append(-1)
        elif target == -1:
            trans_vector.append(4.5)
        elif target == -4:
            trans_vector.append(1)
        elif target == -3:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(3)
        elif target == 1:
            trans_vector.append(5)
        elif target == 2:
            trans_vector.append(6)
        elif target == 3:
            trans_vector.append(7)
        elif target == 5:
            trans_vector.append(9)
        elif target == -1.5:
            trans_vector.append(4)
        elif target == -6:
            trans_vector.append(-2)
        elif target == -7:
            trans_vector.append(-3)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [3]:
def count_number(arr):
    result = {}
    for i in set(arr):
        result[i] = arr.count(i)
    return result

In [4]:
FtoC_list = FtoC([2,3,-2,-2,2,3,5,3,5,6,5,3,5,3,3,2,2,3,-2,-2,2,3,5,3,5,6,5,3,5,3,3,2])
print(FtoC_list)

[-2, -1, -5, -5, -2, -1, 2, -1, 2, 3, 2, -1, 2, -1, -1, -2, -2, -1, -5, -5, -2, -1, 2, -1, 2, 3, 2, -1, 2, -1, -1, -2]


In [5]:
GtoC_list = GtoC([2,2,2,2,0,5,5,3,2,2,2,2,0,1,2,1, 3,2,2,2,0,5,5,3, 2,2,-3,-3,3,3,2,2])
print(GtoC_list)

[-3, -3, -3, -3, 0, 1, 1, -2, -3, -3, -3, -3, 0, -4, -3, -4, -2, -3, -3, -3, 0, 1, 1, -2, -3, -3, -7, -7, -2, -2, -3, -3]


In [6]:
CtoC_list = [2,2,1,2,2,3,3,5, 5,3,3,3, 0,5,5,3, 2,1,1,1, 1,1,1,1]
print(CtoC_list)

[2, 2, 1, 2, 2, 3, 3, 5, 5, 3, 3, 3, 0, 5, 5, 3, 2, 1, 1, 1, 1, 1, 1, 1]


In [7]:
major_list = FtoC_list + GtoC_list + CtoC_list
print(major_list)
count_number(major_list)

[-2, -1, -5, -5, -2, -1, 2, -1, 2, 3, 2, -1, 2, -1, -1, -2, -2, -1, -5, -5, -2, -1, 2, -1, 2, 3, 2, -1, 2, -1, -1, -2, -3, -3, -3, -3, 0, 1, 1, -2, -3, -3, -3, -3, 0, -4, -3, -4, -2, -3, -3, -3, 0, 1, 1, -2, -3, -3, -7, -7, -2, -2, -3, -3, 2, 2, 1, 2, 2, 3, 3, 5, 5, 3, 3, 3, 0, 5, 5, 3, 2, 1, 1, 1, 1, 1, 1, 1]


{0: 4, 1: 12, 2: 13, 3: 8, 5: 4, -1: 12, -7: 2, -5: 4, -4: 2, -3: 16, -2: 11}

In [8]:
#映射顺序 0，1，2，3，5,-1,-2,-3,-4,-5,-7
def major_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 2:
            trans_vector.append(2)
        elif target == 3:
            trans_vector.append(3)
        elif target == 5:
            trans_vector.append(4)
        elif target == -1:
            trans_vector.append(5)
        elif target == -2:
            trans_vector.append(6)
        elif target == -3:
            trans_vector.append(7)
        elif target == -4:
            trans_vector.append(8)
        elif target == -5:
            trans_vector.append(9)
        elif target == -7:
            trans_vector.append(10)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [9]:
reflect_major_list = major_reflect(major_list)
print(reflect_major_list)
len(reflect_major_list)

[6, 5, 9, 9, 6, 5, 2, 5, 2, 3, 2, 5, 2, 5, 5, 6, 6, 5, 9, 9, 6, 5, 2, 5, 2, 3, 2, 5, 2, 5, 5, 6, 7, 7, 7, 7, 0, 1, 1, 6, 7, 7, 7, 7, 0, 8, 7, 8, 6, 7, 7, 7, 0, 1, 1, 6, 7, 7, 10, 10, 6, 6, 7, 7, 2, 2, 1, 2, 2, 3, 3, 4, 4, 3, 3, 3, 0, 4, 4, 3, 2, 1, 1, 1, 1, 1, 1, 1]


88

In [10]:
def markoving(darray, vector):
    num = len(vector)
    for i in range(num-1):   #最后一个不用考虑
        row = vector[i]
        column = vector[i+1]
        darray[row][column] += 1
    return darray

In [11]:
major_array = np.zeros((11,11))
#先处理F1和旋部分：
F1 = reflect_major_list[0:8]
# print(F1)
major_array = markoving(major_array,F1)
# print(major_array)

#先处理F2和旋部分：
F2 = reflect_major_list[8:16]
# print(F2)
major_array = markoving(major_array,F2)
# print(major_array)

#先处理F3和旋部分：
F3 = reflect_major_list[16:24]
# print(F3)
major_array = markoving(major_array,F3)
# print(major_array)

#先处理F4和旋部分：
F4 = reflect_major_list[24:32]
# print(F4)
major_array = markoving(major_array,F4)
# print(major_array)

#先处理G1和旋部分：
G1 = reflect_major_list[32:40]
# print(G1)
major_array = markoving(major_array,G1)
# print(major_array)

#先处理G2和旋部分：
G2 = reflect_major_list[40:48]
# print(G2)
major_array = markoving(major_array,G2)
# print(major_array)

#先处理G3和旋部分：
G3 = reflect_major_list[48:56]
# print(G3)
major_array = markoving(major_array,G3)
# print(major_array)

#先处理G4和旋部分：
G4 = reflect_major_list[56:64]
# print(G4)
major_array = markoving(major_array,G4)
# print(major_array)

#先处理C1和旋部分：
C1 = reflect_major_list[64:72]
# print(C1)
major_array = markoving(major_array,C1)
# print(major_array)

#先处理C2和旋部分：
C2 = reflect_major_list[72:80]
# print(G2)
major_array = markoving(major_array,C2)
# print(major_array)

#先处理C3和旋部分：
C3 = reflect_major_list[80:88]
# print(C3)
major_array = markoving(major_array,C3)
print(major_array)

[[ 0.  2.  0.  0.  1.  0.  0.  0.  1.  0.  0.]
 [ 0.  8.  1.  0.  0.  0.  2.  0.  0.  0.  0.]
 [ 0.  2.  2.  3.  0.  6.  0.  0.  0.  0.  0.]
 [ 1.  0.  2.  3.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  4.  0.  0.  2.  2.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  4.  1.  2.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  0.  0. 10.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.]]


In [12]:
def normalize_matrix(matrix):
    mat_size = matrix.shape[0]
    init_array = np.zeros((mat_size,mat_size))
    sum_row_list=[]
    for i in range(mat_size):
        count=0
        for j in range(mat_size):
            count+=matrix[i][j]
        sum_row_list.append(count)
    for k in range(mat_size):
        if sum_row_list[k] == 0:
            init_array[k][k] = 0
        else:
            init_array[k][k] = 1/sum_row_list[k]
    result = np.dot(init_array,matrix)
    
    return result

def sum_rows(matrix):
    sum_row_list1=[]
    for ii in range(len(matrix)):
        count=0
        for jj in range(len(matrix[ii])):
            count+=matrix[ii][jj]
        sum_row_list1.append(count)
    print(sum_row_list1)

In [13]:
markov_major = normalize_matrix(major_array)
print(markov_major)
sum_rows(markov_major)

[[0.         0.5        0.         0.         0.25       0.
  0.         0.         0.25       0.         0.        ]
 [0.         0.72727273 0.09090909 0.         0.         0.
  0.18181818 0.         0.         0.         0.        ]
 [0.         0.15384615 0.15384615 0.23076923 0.         0.46153846
  0.         0.         0.         0.         0.        ]
 [0.14285714 0.         0.28571429 0.42857143 0.14285714 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.66666667 0.33333333 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.4        0.         0.         0.2
  0.2        0.         0.         0.2        0.        ]
 [0.         0.         0.         0.         0.         0.57142857
  0.14285714 0.28571429 0.         0.         0.        ]
 [0.2        0.         0.         0.         0.         0.
  0.         0.66666667 0.06666667 0.         0.06666667]
 [0.         0.         0.         0.  

In [14]:
#邻接矩阵

def generate_adj(darray, vector):
    num = len(vector)
    for i in range(num-1):
        row = vector[i]
        column = vector[i+1]
        darray[row][column] = 1
    return darray

In [15]:
adj_major = np.zeros((11,11))
#先处理F1和旋部分：
adj_major = generate_adj(adj_major,F1)
# print(adj_major)

#先处理F2和旋部分：
adj_major = generate_adj(adj_major,F2)
# print(adj_major)

#先处理F3和旋部分：
adj_major = generate_adj(adj_major,F3)
# print(adj_major)

#先处理F4和旋部分：
adj_major = generate_adj(adj_major,F4)
# print(adj_major)

#先处理G1和旋部分：
adj_major = generate_adj(adj_major,G1)
# print(adj_major)

#先处理G2和旋部分：
adj_major = generate_adj(adj_major,G2)
# print(adj_major)

#先处理G3和旋部分：
adj_major = generate_adj(adj_major,G3)
# print(adj_major)

#先处理G4和旋部分：
adj_major = generate_adj(adj_major,G4)
# print(adj_major)

#先处理C1和旋部分：
adj_major = generate_adj(adj_major,C1)
# print(adj_major)

#先处理C2和旋部分：
adj_major = generate_adj(adj_major,C2)
# print(adj_major)

#先处理C3和旋部分：
adj_major = generate_adj(adj_major,C3)
print(adj_major)

[[0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]]


In [16]:
#邻接矩阵调参数
k=3
x = 0.8

i = 0
Iter_adj_major = 1
for i in range(k):
    Iter_adj_major = np.dot(adj_major,Iter_adj_major)
    
Iter_adj_major = normalize_matrix(Iter_adj_major)

markov_major_final = x*markov_major + (1-x)*Iter_adj_major
sum_rows(markov_major_final)
print(markov_major_final)

[1.0000000000000002, 1.0, 0.9999999999999999, 0.9999999999999999, 1.0, 1.0, 0.9999999999999998, 1.0, 1.0, 0.9999999999999999, 0.9999999999999999]
[[0.02       0.42       0.03       0.03       0.22       0.02
  0.02       0.02       0.21       0.         0.01      ]
 [0.01111111 0.6040404  0.11161616 0.01666667 0.00555556 0.03333333
  0.17878788 0.01666667 0.00555556 0.01111111 0.00555556]
 [0.00784314 0.1505279  0.16229261 0.21206637 0.01568627 0.40060332
  0.02745098 0.00784314 0.00392157 0.01176471 0.        ]
 [0.12928571 0.025      0.26857143 0.38285714 0.14928571 0.015
  0.015      0.005      0.005      0.005      0.        ]
 [0.02105263 0.02105263 0.03157895 0.58596491 0.31929825 0.01052632
  0.         0.         0.01052632 0.         0.        ]
 [0.00909091 0.01363636 0.35181818 0.01363636 0.00454545 0.19636364
  0.20090909 0.01818182 0.00454545 0.18272727 0.00454545]
 [0.01176471 0.01176471 0.01764706 0.00588235 0.00588235 0.48655462
  0.14957983 0.25798319 0.01764706 0.0176

In [17]:
#开始进行迭代
init_array = np.array([1/11,1/11,1/11,1/11,1/11,1/11,1/11,1/11,1/11,1/11,1/11]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_major_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.03919529]
 [0.11654746]
 [0.09150222]
 [0.11409762]
 [0.06875033]
 [0.11321648]
 [0.14033889]
 [0.16490983]
 [0.03632084]
 [0.06052274]
 [0.05459831]]
1 	 [[0.05286496]
 [0.11149473]
 [0.10691547]
 [0.11017989]
 [0.0543959 ]
 [0.13991052]
 [0.12739056]
 [0.17165292]
 [0.02916757]
 [0.05251091]
 [0.04351658]]
2 	 [[0.05328978]
 [0.11628042]
 [0.11673579]
 [0.10420507]
 [0.05245872]
 [0.14425983]
 [0.12203181]
 [0.16622958]
 [0.03178938]
 [0.05372219]
 [0.03899744]]
3 	 [[0.05164831]
 [0.1205996 ]
 [0.11856148]
 [0.10294191]
 [0.05117623]
 [0.14633117]
 [0.12153849]
 [0.16403049]
 [0.03146275]
 [0.0550195 ]
 [0.03669007]]
4 	 [[0.05109431]
 [0.12271611]
 [0.11960069]
 [0.10212447]
 [0.05023447]
 [0.14725249]
 [0.12211998]
 [0.16241499]
 [0.03093434]
 [0.05597495]
 [0.03553322]]
5 	 [[0.05070719]
 [0.12386104]
 [0.12005864]
 [0.10150176]
 [0.0496891 ]
 [0.14814946]
 [0.12262275]
 [0.16123237]
 [0.0306857 ]
 [0.05657683]
 [0.03491518]]
6 	 [[0.05042452]
 [0.12442617]
 [0.12037945]


In [18]:
major_list = [0,1,2,3,5,-1,-2,-3,-4,-5,-7]
p_list1 = []

i = 0
for i in range(len(major_list)):
    target_list = res[i]
    p_list1.append(target_list[0])
print(p_list1)

# i = 0
# count = 0
# for i in range(len(p_list)):
#     count += p_list[i]
# print(count)
# 主歌大调：K=3，x=0.8
major_88 = np.random.choice(major_list, 88, p=p_list1)

[0.04994983400062469, 0.12464604848420074, 0.12083774484002649, 0.10002287621704979, 0.048594249284639145, 0.15008486122119677, 0.12395228953016024, 0.1595731556996349, 0.030238156851994928, 0.05799138985751119, 0.03410939401296194]


In [19]:
#F1
major1 = CtoF(major_88[0:4])
#G1
major2 = CtoG(major_88[4:8])
#F2
major3 = CtoF(major_88[8:12])
#G2
major4 = CtoG(major_88[12:16])
#C1
major5 = major_88[16:20]
major5 = major5.tolist()
#C2
major6 = major_88[20:24]
major6 = major6.tolist()


#F3
major7 = CtoF(major_88[24:28])
#G3
major8 = CtoG(major_88[28:32])
#F4
major9 = CtoF(major_88[32:36])
#G4
major10 = CtoG(major_88[36:40])
#C3
major11 = major_88[40:41]
major11 = major11.tolist()
#C4
major12 = [1,1,1,1,1,1,1]

In [20]:
#小调分割线

In [21]:
def EmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 2:
            trans_vector.append(-1.5)
        elif target == 3:
            trans_vector.append(1)
        elif target == 5:
            trans_vector.append(2.5)
        elif target == -3:
            trans_vector.append(-5.5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoEm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == -2.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-6)
        elif target == -7:
            trans_vector.append(-5)
        elif target == -1.5:
            trans_vector.append(2)
        elif target == 1:
            trans_vector.append(3)
        elif target == -4:
            trans_vector.append(-2)
        elif target == -3:
            trans_vector.append(-1)
        elif target == -5.5:
            trans_vector.append(-3)
        elif target == 2.5:
            trans_vector.append(5)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


def AmtoC(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 1:
            trans_vector.append(-5.5)
        elif target == 2:
            trans_vector.append(-4)
        elif target == 3:
            trans_vector.append(-3)
        elif target == 4:
            trans_vector.append(-2.5)
        elif target == 5:
            trans_vector.append(-1.5)
        elif target == 6:
            trans_vector.append(1)
        elif target == 7:
            trans_vector.append(2)
        elif target == -2:
            trans_vector.append(-7)
        elif target == -3:
            trans_vector.append(-8.5)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

def CtoAm(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == -5.5:
            trans_vector.append(1)
        elif target == -8.5:
            trans_vector.append(-3)
        elif target == -7:
            trans_vector.append(-2)
        elif target == -4:
            trans_vector.append(2)
        elif target == -3:
            trans_vector.append(3)
        elif target == -2.5:
            trans_vector.append(4)
        elif target == 2.5:
            trans_vector.append(8)
        elif target == -1.5:
            trans_vector.append(5)
        elif target == 1:
            trans_vector.append(6)
        elif target == 2:
            trans_vector.append(7)
        elif target == 0:
            trans_vector.append(0)
        else:
            print(target)
            print("没有被添加")
    return trans_vector

In [22]:
EmtoC_list = EmtoC([2,3,-3,-3, 2,3,5,2])
AmtoC_list = AmtoC([1,1,1,1,  0,1,2,3])
EmtoC_list2 = EmtoC([2,3,-3,-3, 2,3,5,2])
AmtoC_list2 = AmtoC([1,1,1,1,  0,1,2,3])

minor_list = EmtoC_list+AmtoC_list+EmtoC_list2+AmtoC_list2
count_number(minor_list)

{0: 2, 1: 4, 2.5: 2, -5.5: 14, -4: 2, -3: 2, -1.5: 6}

In [23]:
#映射顺序 0，1，2.5, -1.5,-3,-4,-5.5
def minor_reflect(vector):
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target == 0:
            trans_vector.append(0)
        elif target == 1:
            trans_vector.append(1)
        elif target == 2.5:
            trans_vector.append(2)
        elif target == -1.5:
            trans_vector.append(3)
        elif target == -3:
            trans_vector.append(4)
        elif target == -4:
            trans_vector.append(5)
        elif target == -5.5:
            trans_vector.append(6)
        else:
            print(target)
            print("没有被添加")
    return trans_vector


In [24]:
reflect_minor_list = minor_reflect(minor_list)
print(reflect_minor_list)
len(reflect_minor_list)

[3, 1, 6, 6, 3, 1, 2, 3, 6, 6, 6, 6, 0, 6, 5, 4, 3, 1, 6, 6, 3, 1, 2, 3, 6, 6, 6, 6, 0, 6, 5, 4]


32

In [25]:
minor_array = np.zeros((7,7))

#先处理Em1和旋部分：
Em1 = reflect_minor_list[0:8]
# print(Em1)
minor_array = markoving(minor_array,Em1)
# print(minor_array)

#先处理Am1和旋部分：
Am1 = reflect_minor_list[8:16]
# print(Am1)
minor_array = markoving(minor_array,Am1)
# print(minor_array)

#先处理Em2和旋部分：
Em2 = reflect_minor_list[16:24]
# print(Em2)
minor_array = markoving(minor_array,Em2)
# print(minor_array)

#先处理Am2和旋部分：
Am2 = reflect_minor_list[24:32]
# print(Am2)
minor_array = markoving(minor_array,Am2)
print(minor_array)

[[0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 2. 0. 0. 0. 2.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0.]
 [2. 0. 0. 2. 0. 2. 8.]]


In [26]:
markov_minor = normalize_matrix(minor_array)
print(markov_minor)
sum_rows(markov_minor)

[[0.         0.         0.         0.         0.         0.
  1.        ]
 [0.         0.         0.5        0.         0.         0.
  0.5       ]
 [0.         0.         0.         1.         0.         0.
  0.        ]
 [0.         1.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         1.         0.
  0.        ]
 [0.14285714 0.         0.         0.14285714 0.         0.14285714
  0.57142857]]
[1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0]


In [27]:
#第五行为空行，调一下参数

modify_line = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7])
markov_minor[[4],:] = modify_line
print(markov_minor)
sum_rows(markov_minor)

[[0.         0.         0.         0.         0.         0.
  1.        ]
 [0.         0.         0.5        0.         0.         0.
  0.5       ]
 [0.         0.         0.         1.         0.         0.
  0.        ]
 [0.         1.         0.         0.         0.         0.
  0.        ]
 [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
  0.14285714]
 [0.         0.         0.         0.         1.         0.
  0.        ]
 [0.14285714 0.         0.         0.14285714 0.         0.14285714
  0.57142857]]
[1.0, 1.0, 1.0, 1.0, 0.9999999999999998, 1.0, 1.0]


In [28]:
#邻接矩阵
adj_minor = np.zeros((7,7))

adj_minor = generate_adj(adj_minor,Em1)
adj_minor = generate_adj(adj_minor,Am1)
adj_minor = generate_adj(adj_minor,Em2)
adj_minor = generate_adj(adj_minor,Am2)
print(adj_minor)

[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1. 1.]]


In [29]:
k =2
x = 0.8

i = 0
Iter_adj_minor = 1
for i in range(k):
    Iter_adj_minor = np.dot(adj_minor,Iter_adj_minor)

print(Iter_adj_minor)
Iter_adj_minor = normalize_matrix(Iter_adj_minor)
# print(Iter_adj_minor)
# sum_rows(Iter_adj_minor)


#第5行为空行，调一下参数
modify_line = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7])
Iter_adj_minor[[4],:] = modify_line
# print(Iter_adj_major)

#第6行为空行，调一下参数
modify_line = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7])
Iter_adj_minor[[5],:] = modify_line
# print(Iter_adj_major)


markov_minor_final = x*markov_minor + (1-x)*Iter_adj_minor
print(markov_minor_final)
sum_rows(markov_minor_final)

[[1. 0. 0. 1. 0. 1. 1.]
 [1. 0. 0. 2. 0. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 1. 2.]]
[[0.05       0.         0.         0.05       0.         0.05
  0.85      ]
 [0.04       0.         0.4        0.08       0.         0.04
  0.44      ]
 [0.         0.2        0.         0.8        0.         0.
  0.        ]
 [0.         0.8        0.1        0.         0.         0.
  0.1       ]
 [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714 0.14285714
  0.14285714]
 [0.02857143 0.02857143 0.02857143 0.02857143 0.82857143 0.02857143
  0.02857143]
 [0.14285714 0.02857143 0.         0.14285714 0.02857143 0.14285714
  0.51428571]]
[1.0, 1.0, 1.0, 1.0, 0.9999999999999998, 1.0, 1.0]


In [30]:
#开始进行迭代
init_array = np.array([1/7,1/7,1/7,1/7,1/7,1/7,1/7]).reshape((-1,1))   #变成列向量
restmp = init_array

i = 0
for i in range(50):
    res = np.dot(markov_minor_final.T,restmp)
    print (i, "\t", res)
    restmp = res

0 	 [[0.0577551 ]
 [0.17142857]
 [0.09591837]
 [0.1777551 ]
 [0.14285714]
 [0.0577551 ]
 [0.29653061]]
1 	 [[0.07416472]
 [0.19191837]
 [0.10840525]
 [0.15775656]
 [0.07673469]
 [0.07416472]
 [0.31685569]]
2 	 [[0.06973116]
 [0.17002041]
 [0.10562409]
 [0.16413209]
 [0.08146589]
 [0.06973116]
 [0.3392952 ]]
3 	 [[0.07238842]
 [0.17575494]
 [0.09805168]
 [0.16368851]
 [0.07910938]
 [0.07238842]
 [0.33861865]]
4 	 [[0.07239329]
 [0.17360554]
 [0.10004041]
 [0.15786483]
 [0.08095513]
 [0.07239329]
 [0.3427475 ]]
5 	 [[0.07316121]
 [0.16972613]
 [0.0988621 ]
 [0.16013776]
 [0.08134082]
 [0.07316121]
 [0.34361076]]
6 	 [[0.07324479]
 [0.17141052]
 [0.09761467]
 [0.15912352]
 [0.08205686]
 [0.07324479]
 [0.34330485]]
7 	 [[0.07337733]
 [0.17044558]
 [0.09829168]
 [0.15832548]
 [0.08221966]
 [0.07337733]
 [0.34396295]]
8 	 [[0.07346642]
 [0.16998839]
 [0.09785294]
 [0.15891758]
 [0.08237154]
 [0.07346642]
 [0.34393672]]
9 	 [[0.07347308]
 [0.17039782]
 [0.09775352]
 [0.15855496]
 [0.0824663 ]

In [31]:
#映射顺序 0，1，2.5, -1.5,-3,-4,-5.5
minor_list = [0,1,2.5,-1.5,-3,-4,-5.5]
p_list2 = []

i = 0
for i in range(len(minor_list)):
    target_list = res[i]
    p_list2.append(target_list[0])
print(p_list2)

#主歌大调：K=3，x=0.8
minor_32 = np.random.choice(minor_list, 32, p=p_list2)

[0.07351181965695879, 0.17011642840080976, 0.09779156592078891, 0.15854972952926252, 0.08252778731890956, 0.07351181965695879, 0.3439908495163103]


In [32]:
minor1 = CtoEm(minor_32[0:4])
minor2 = CtoAm(minor_32[4:8])
minor3 = CtoEm(minor_32[8:12])
minor4 = CtoAm(minor_32[12:16])

In [33]:
fuge_seq = major1 + major2 + minor1 + minor2 + major3 + major4 + major5 + major6 + major7 + major8 + minor3 + minor4 + major9 + major10 + major11 + major12
print(fuge_seq)
len(fuge_seq)

[6, 5, 4, 8, 4.5, 7, 2, 7, -2, 3, 2, -1, 1, 1, 3, 5, -4, 2, 4, 1, 5, 4.5, 2, 5, -5, -2, -1, -5, 5, 0, -7, -1, 0, 4, 4, 5, 5, -1, -1, 6, -3, -3, 3, 5, 5, 1, 3, 5, -1.5, 5, 0, 1, 0, 2, 4.5, 6, -4, 1, 1, 1, 1, 1, 1, 1]


64

In [34]:
def find_nearest(num, vector):
    result = num
    mark = 100
    length = len(vector)
    for i in range(length):
        instance = abs(num - vector[i])
        if mark > instance:
            mark = instance
            result = vector[i]
        else:
            continue
    return result

def post_process(vector):
    num = len(vector)
    five_list = [1,2,3,5,6, 8,9,10,12,13, -2,-3,-5,-6,-7,-9]
    C_list = [1,3,5,8,10,12,-7,-5,-3]
    Am_list = [1,3,6,8,10,-2,-5,-7]
    Em_list = [3,5,10,12,-3,-5]
    F_list = [1,6,8,13,-2,-7]
    G_list = [2,5,9,12,-3,-6]
    for i in range(num):
        target = vector[i]
#         int_part = math.floor(target/7)
#         remain_part = target - int_part*7
        if target == 0:
            vector[i] = vector[i-1]
            target = vector[i-1]
        if target in  five_list:
            other = 1
        else:
            if (i>=0 & i<4)|(i>=16 & i<20)|(i>=32 & i<36)|(i>=48 & i<52):
                vector[i] = find_nearest(vector[i],F_list)
            elif (i>=4 & i<8)|(i>=20 & i<24)|(i>=36 & i<40)|(i>=52 & i<56):
                #G chord
                vector[i] = find_nearest(vector[i],G_list)
            elif (i>=8 & i<12)|(i>=40 & i<44):
                #Em chord
                vector[i] = find_nearest(vector[i],Em_list)
            elif (i>=12 & i<16)|(i>=44 & i<48):
                #Am chord
                vector[i] = find_nearest(vector[i],Am_list)
            elif (i>=24 & i<32)|(i>=56 & i<64):
                #C chord
                vector[i] = find_nearest(vector[i],C_list)
                            
    #律动感
    vector[13] = vector[12]
    vector[29] = vector[28]
    vector[45] = vector[44]
    return vector

In [35]:
postprocessing_zhuge = post_process(fuge_seq)
print(postprocessing_zhuge)

[6, 5, 6, 8, 6, 6, 2, 6, -2, 3, 2, -2, 1, 1, 3, 5, -2, 2, 6, 1, 5, 6, 2, 5, -5, -2, -2, -5, 5, 5, -7, -2, -2, 6, 6, 5, 5, -2, -2, 6, -3, -3, 3, 5, 5, 5, 3, 5, -2, 5, 5, 1, 1, 2, 6, 6, -2, 1, 1, 1, 1, 1, 1, 1]


In [36]:
import mido
from mido import Message, MidiFile, MidiTrack

In [37]:
import math

def map_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 4:
        result = 6
    elif num == 4.5:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result   


def map2_remain(num):
    if num == 1:
        result = 1
    elif num == 1.5:
        result = 2
    elif num == 2:
        result = 3
    elif num == 2.5:
        result = 4
    elif num == 3:
        result = 5
    elif num == 3.5:
        result = 6
    elif num == 4:
        result = 7
    elif num == 5:
        result = 8
    elif num == 5.5:
        result = 9
    elif num == 6:
        result = 10
    elif num == 6.5:
        result = 11
    elif num == 0:
        result = 0
    return result 
        
        
def toMidi(vector):
    
    num = len(vector)
    trans_vector = []
    for i in range(num):
        target = vector[i]
        if target > 0:
            base = 59   #基数是59
            int_part = math.floor(target)     #得到target的整数部分
            times = math.floor(int_part/7)    #整数部分是由多少个7组成的
            base += times*12

            remain = target - times*7        #得到剩余部分
            base += map_remain(remain)
            trans_vector.append(base)
        else:  #target < 0
            base = 60   #基数是60
            target = abs(target)
            int_part = math.floor(target)
            times = math.floor(int_part/7)
            base -= times*12
            
            remain = target - times*7
            base -= map2_remain(remain)
            trans_vector.append(base)
    return trans_vector

In [38]:
mid = MidiFile()       #给自己的文件定的.mid后缀
track = MidiTrack()    #定义声部，一个MidoTrack()就是一个声部

In [39]:
def beat(time):            #与mido的拍子互换  
    time /= 60 * 1000  
    time = 1/time  
    return time  

def yin(yin,pai,qian=0,unit = track, liang=64,qi=2): #yin是音，pai是指时间（节拍），
    if type(yin)== str:               #qian是是音前多少拍
        yin = num(yin)                #liang是音量

    unit.append(Message('program_change',channel=0,program=qi,time=0))
    unit.append(Message('note_on',note=yin,velocity=liang,time=qian,channel=0))
    unit.append(Message('note_off',note=yin,velocity=liang,time=int(beat(pai)),channel=0))

In [40]:
fuge1 = [5, 6, 3, 1, 2, 6, 6, 6, 5, 5, 3, -3, 1, 1, 6, 2, 3, 1, 5, 6, 6, 6, 6, 2, 1, -2, 1, -5, -3, -3, -3, -2, -2, 6, 6, 5, 6, 5, 6, 6, -3, 5, -2, 5, 1, 1, 1, 5, 5, 2, 3, 3, 3, 2, 3, 2, -3, 1, 1, 1, 1, 1, 1, 1]
fuge2 = [2, 1, -2, 1, 2, 1, 9, 3, 3, 2, -3, 3, 1, 1, 2, 3, 1, 1, 8, 8, -2, 6, 6, 6, -7, -2, -2, -2, -2, -2, 3, -2, 6, -2, 5, 2, 6, 3, 6, -2, -3, -3, -3, 5, 3, 3, 6, 5, 1, 3, 1, 8, 3, 5, 6, 2, -2, 1, 1, 1, 1, 1, 1, 1]
fuge3 = [6, 5, 6, 8, 6, 6, 2, 6, -2, 3, 2, -2, 1, 1, 3, 5, -2, 2, 6, 1, 5, 6, 2, 5, -5, -2, -2, -5, 5, 5, -7, -2, -2, 6, 6, 5, 5, -2, -2, 6, -3, -3, 3, 5, 5, 5, 3, 5, -2, 5, 5, 1, 1, 2, 6, 6, -2, 1, 1, 1, 1, 1, 1, 1]

In [41]:
fuge_sequence = fuge3
midi_sequence = toMidi(fuge_sequence)
five_list = [1,2,3,5,6, 8,9,10,12,13, -2,-3,-5,-6,-7,-9]
C_list = [1,3,5,8,10,12,-7,-5,-3]
Am_list = [1,3,6,8,10,-2,-5,-7]
Em_list = [3,5,10,12,-3,-5]
F_list = [1,6,8,13,-2,-7]
G_list = [2,5,9,12,-3,-6]
i=0
for i in range(64):    #16个小节，每小节8拍，一共128
    target = fuge_sequence[i]
    midi_target = midi_sequence[i]
    if (target>= 6)&(target<=7):    #框定在一个区间
        target -= 8
        midi_target = midi_sequence[i]-12
    elif (target > 7):
        target -= 7
        midi_target = midi_sequence[i]-12
    elif (target < -3) & (target>=-7):
        target += 8
        midi_target = midi_sequence[i]+12
    elif (target<-7):
        target +=7
        midi_target = midi_sequence[i]+12
#     else:
#         continue
    
    if i == 63:
        next_target = target
    else:
        next_target = fuge_sequence[i+1]
        if (next_target>= 6)&(next_target<=7):    #框定在一个区间
            next_target -= 8
        elif (next_target > 7):
            next_target -= 7
        elif (next_target < -3) & (next_target>=-7):
            next_target += 8
        elif (next_target<-7):
            next_target +=7
#         else:
#             continue
        
    distance = abs(target-next_target)
    if target > next_target:
        big = target
        small = next_target
    else:
        big = next_target
        small = target
        
    if distance >=5:
        if (i>=24 & i<32)|(i>=56 & i<64):
            #CCCCCC
#             new_Arr = np.random.choice(major_list, 1, p=p_list1)
#             new_list = new_Arr.tolist()
#             new = new_list[0]
            while(True):
                new_Arr = np.random.choice(major_list, 1, p=p_list1)
                new_list = new_Arr.tolist()
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue   
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, C_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)                 
                
        elif (i>=12 & i<16)|(i>=44 & i<48):
            #amamamamamam
            while(True):
                new_Arr = np.random.choice(minor_list, 1, p=p_list2)
                new_list = new_Arr.tolist()
                new_list = CtoAm(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue   
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, Am_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)    
        elif (i>=0 & i<4)|(i>=16 & i<20)|(i>=32 & i<36)|(i>=48 & i<52):
            #FFFFFF
#             new_Arr = np.random.choice(major_list, 1, p=p_list1)
#             new_list = new_Arr.tolist()
#             new_list = CtoF(new_list)
#             new = new_list[0]
            while(True):
                new_Arr = np.random.choice(major_list, 1, p=p_list1)
                new_list = new_Arr.tolist()
                new_list = CtoF(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue        
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, F_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)    
        elif (i>=4 & i<8)|(i>=20 & i<24)|(i>=36 & i<40)|(i>=52 & i<56):
            #GGGGG
            while(True):
                new_Arr = np.random.choice(major_list, 1, p=p_list1)
                new_list = new_Arr.tolist()
                new_list = CtoG(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue            
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, G_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
        elif (i>=8 & i<12)|(i>=40 & i<44):
            #EMEMEMEMEM
            while(True):
                new_Arr = np.random.choice(minor_list, 1, p=p_list2)
                new_list = new_Arr.tolist()
                new_list = CtoEm(new_list)
                new = new_list[0]
                if (new<big)&(new>small):
                    break
                else:
                    continue     
            midi_new_list = toMidi(new_list)
            midi_new = midi_new_list[0]
            if new in five_list:
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
            else:
                new = find_nearest(new, Em_list)
                new_list = [new]
                midi_new_list = toMidi(new_list)
                midi_new = midi_new_list[0]
                yin(midi_target,160, 0,track,80,2)  
                yin(midi_new,160, 0,track,80,2)  
    else:
        yin(midi_target,80, 0,track,80,2)   

In [42]:
track1 = MidiTrack()
track2 = MidiTrack()
track3 = MidiTrack()
def C_chord(track1,track2,track3):
    C_sq = toMidi([1,3,5])
    yin(C_sq[0],20, 0,track1,80,2)
    yin(C_sq[1],20, 0,track2,80,2)
    yin(C_sq[2],20, 0,track3,80,2)

def F_chord(track1,track2,track3):
    sq = toMidi([-4,-2,1])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)
    
def G_chord(track1,track2,track3):
    sq = toMidi([-3,-1,2])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)
    
def Em_chord(track1,track2,track3):
    sq = toMidi([-5,-3,-1])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)

def Am_chord(track1,track2,track3):
    sq = toMidi([-2,1,3])
    yin(sq[0],20, 0,track1,80,2)
    yin(sq[1],20, 0,track2,80,2)
    yin(sq[2],20, 0,track3,80,2)
    
F_chord(track1,track2,track3)
G_chord(track1,track2,track3)
Em_chord(track1,track2,track3)
Am_chord(track1,track2,track3)
F_chord(track1,track2,track3)
G_chord(track1,track2,track3)
C_chord(track1,track2,track3)
C_chord(track1,track2,track3)
F_chord(track1,track2,track3)
G_chord(track1,track2,track3)
Em_chord(track1,track2,track3)
Am_chord(track1,track2,track3)
F_chord(track1,track2,track3)
G_chord(track1,track2,track3)
C_chord(track1,track2,track3)
C_chord(track1,track2,track3)

In [43]:
mid.tracks.append(track)
mid.tracks.append(track1)
mid.tracks.append(track2)
mid.tracks.append(track3)

mid.save('C:\\Users\\Administrator\\Desktop\\2020Summer\\qhc副歌3.mid')